/** Каталожные приводы «НЕМАН», данные карточек 2026 года. */
import { t2, type Component } from '../model';
import { VALVE_CLASS_ID } from '../valve/class';

const CATALOG_FILE = 'HEMAH_Каталог основных видов_2026 [lUHZBf].pdf';

export const NEMAN_SMOKE_COMPONENTS: Component[] = [
  {
    id: "cmp-neman-ble24-10",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLE24-10",
    title: t2("Электропривод BLE24-10"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": false, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5,5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "0,8", unit: "Вт" },
            { label: t2("Температура хранения"), value: "-40...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Масса"), value: "≈1800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "86–87", edition: '2026' }, sourcePdfPage: 44,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-ble230-10",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLE230-10",
    title: t2("Электропривод BLE230-10"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 10.0, "springReturn": false, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "5", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "0,6", unit: "Вт" },
            { label: t2("Температура хранения"), value: "-40...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Масса"), value: "≈1800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "86–87", edition: '2026' }, sourcePdfPage: 44,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-ble24-15",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLE24-15",
    title: t2("Электропривод BLE24-15"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 15.0, "springReturn": false, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "15", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5,5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "0,8", unit: "Вт" },
            { label: t2("Температура хранения"), value: "-40...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Масса"), value: "≈1800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "88–89", edition: '2026' }, sourcePdfPage: 45,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-ble230-15",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLE230-15",
    title: t2("Электропривод BLE230-15"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 15.0, "springReturn": false, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "15", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "5", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "0,6", unit: "Вт" },
            { label: t2("Температура хранения"), value: "-40...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Масса"), value: "≈1800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "88–89", edition: '2026' }, sourcePdfPage: 45,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-be24-40",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BE24-40",
    title: t2("Электропривод BE24-40"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 40.0, "springReturn": false, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "40", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "30", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "12", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "1,5", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Масса"), value: "≈2300", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "90–91", edition: '2026' }, sourcePdfPage: 46,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-be230-40",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BE230-40",
    title: t2("Электропривод BE230-40"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 40.0, "springReturn": false, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "40", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "30", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "12", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "1,5", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Масса"), value: "≈2300", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "90–91", edition: '2026' }, sourcePdfPage: 46,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
];
