/** Каталожные приводы «НЕМАН», данные карточек 2026 года. */
import { t2, type Component } from '../model';
import { VALVE_CLASS_ID } from '../valve/class';

const CATALOG_FILE = 'HEMAH_Каталог основных видов_2026 [lUHZBf].pdf';

export const NEMAN_SPRING_COMPONENTS: Component[] = [
  {
    id: "cmp-neman-tf230-3",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "TF230-3",
    title: t2("Электропривод TF230-3"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 3.0, "springReturn": true, "control": "Открыто/закрыто", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "3", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3,5", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<25...45с/90°" },
      { label: t2("Время пружинного возврата"), value: "<15 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "≈1200", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "44–45", edition: '2026' }, sourcePdfPage: 23,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-tf230-s2-3",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "TF230-S2-3",
    title: t2("Электропривод TF230-S2-3"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 3.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "3", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3,5", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<25...45с/90°" },
      { label: t2("Время пружинного возврата"), value: "<15 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "≈1200", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "44–45", edition: '2026' }, sourcePdfPage: 23,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-tf24-3",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "TF24-3",
    title: t2("Электропривод TF24-3"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 3.0, "springReturn": true, "control": "Открыто/закрыто", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "3", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3,5", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<25...45с/90°" },
      { label: t2("Время пружинного возврата"), value: "<15 с при –20…+50°С; <60 с" },
      { label: t2("Масса"), value: "≈1200", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "46–47", edition: '2026' }, sourcePdfPage: 24,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-tf24-s2-3",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "TF24-S2-3",
    title: t2("Электропривод TF24-S2-3"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 3.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "3", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3,5", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<25...45с/90°" },
      { label: t2("Время пружинного возврата"), value: "<15 с при –20…+50°С; <60 с" },
      { label: t2("Масса"), value: "≈1200", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "46–47", edition: '2026' }, sourcePdfPage: 24,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lf230-5",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LF230-5",
    title: t2("Электропривод LF230-5"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 5.0, "springReturn": true, "control": "Открыто/закрыто", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "8", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<70с/90°" },
      { label: t2("Время пружинного возврата"), value: "<20 с при –20…+50°С; <60 с" },
      { label: t2("Масса"), value: "≈1900", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "48–49", edition: '2026' }, sourcePdfPage: 25,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lf230-s2-5",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LF230-S2-5",
    title: t2("Электропривод LF230-S2-5"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 5.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "8", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<70с/90°" },
      { label: t2("Время пружинного возврата"), value: "<20 с при –20…+50°С; <60 с" },
      { label: t2("Масса"), value: "≈1900", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "48–49", edition: '2026' }, sourcePdfPage: 25,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lf24-5",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LF24-5",
    title: t2("Электропривод LF24-5"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 5.0, "springReturn": true, "control": "Открыто/закрыто", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "8", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<70с/90°" },
      { label: t2("Время пружинного возврата"), value: "<20 с при –20…+50°С; <60 с" },
      { label: t2("Масса"), value: "≈1800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "50–51", edition: '2026' }, sourcePdfPage: 26,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lf24-s2-5",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LF24-S2-5",
    title: t2("Электропривод LF24-S2-5"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 5.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "8", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<70с/90°" },
      { label: t2("Время пружинного возврата"), value: "<20 с при –20…+50°С; <60 с" },
      { label: t2("Масса"), value: "≈1800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "50–51", edition: '2026' }, sourcePdfPage: 26,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lf24-sr-5",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LF24-SR-5",
    title: t2("Электропривод LF24-SR-5"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 5.0, "springReturn": true, "control": "Плавное", "signal": "2…10 В DC", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Управляющий сигнал"), value: "2…10 В DC" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<100с/90°" },
      { label: t2("Время пружинного возврата"), value: "<20 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "≈1900", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "52–53", edition: '2026' }, sourcePdfPage: 27,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lf24-srz-5",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LF24-SRZ-5",
    title: t2("Электропривод LF24-SRZ-5"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 5.0, "springReturn": true, "control": "Плавное", "signal": "0…10 В DC", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Управляющий сигнал"), value: "0…10 В DC" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<100с/90°" },
      { label: t2("Время пружинного возврата"), value: "<20 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "≈1900", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "52–53", edition: '2026' }, sourcePdfPage: 27,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nf230",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NF230",
    title: t2("Электропривод NF230"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 10.0, "springReturn": true, "control": "Открыто/закрыто", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<100с/90°" },
      { label: t2("Время пружинного возврата"), value: "<25 с при –20…+50°С; <60 с" },
      { label: t2("Масса"), value: "≈2300", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "54–55", edition: '2026' }, sourcePdfPage: 28,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nf230-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NF230-S2",
    title: t2("Электропривод NF230-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 10.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<100с/90°" },
      { label: t2("Время пружинного возврата"), value: "<25 с при –20…+50°С; <60 с" },
      { label: t2("Масса"), value: "≈2300", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "54–55", edition: '2026' }, sourcePdfPage: 28,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nf24",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NF24",
    title: t2("Электропривод NF24"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": true, "control": "Открыто/закрыто", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<100с/90°" },
      { label: t2("Время пружинного возврата"), value: "<25 с при –20…+50°С; <60 с" },
      { label: t2("Масса"), value: "≈2300", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "56–57", edition: '2026' }, sourcePdfPage: 29,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nf24-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NF24-S2",
    title: t2("Электропривод NF24-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<100с/90°" },
      { label: t2("Время пружинного возврата"), value: "<25 с при –20…+50°С; <60 с" },
      { label: t2("Масса"), value: "≈2300", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "56–57", edition: '2026' }, sourcePdfPage: 29,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nf24-sr",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NF24-SR",
    title: t2("Электропривод NF24-SR"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": true, "control": "Плавное", "signal": "2…10 В DC", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Управляющий сигнал"), value: "2…10 В DC" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "12", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "6", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<120с/90°" },
      { label: t2("Время пружинного возврата"), value: "<25 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "≈3000", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "58–59", edition: '2026' }, sourcePdfPage: 30,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nf24-srz",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NF24-SRZ",
    title: t2("Электропривод NF24-SRZ"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": true, "control": "Плавное", "signal": "0…10 В DC", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Управляющий сигнал"), value: "0…10 В DC" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "12", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "6", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<120с/90°" },
      { label: t2("Время пружинного возврата"), value: "<25 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "≈3000", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "58–59", edition: '2026' }, sourcePdfPage: 30,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sf230",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SF230",
    title: t2("Электропривод SF230"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 20.0, "springReturn": true, "control": "Открыто/закрыто", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "40", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "20", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "2,5", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Время пружинного возврата"), value: "<30 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "<3200", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "60–61", edition: '2026' }, sourcePdfPage: 31,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sf230-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SF230-S2",
    title: t2("Электропривод SF230-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 20.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "40", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "20", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "2,5", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Время пружинного возврата"), value: "<30 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "<3200", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "60–61", edition: '2026' }, sourcePdfPage: 31,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sf24",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SF24",
    title: t2("Электропривод SF24"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 20.0, "springReturn": true, "control": "Открыто/закрыто", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "40", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "20", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "2,5", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Время пружинного возврата"), value: "<30 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "<3200", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "62–63", edition: '2026' }, sourcePdfPage: 32,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sf24-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SF24-S2",
    title: t2("Электропривод SF24-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 20.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "40", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "20", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "2,5", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Время пружинного возврата"), value: "<30 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "<3200", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "62–63", edition: '2026' }, sourcePdfPage: 32,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sf24-sr",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SF24-SR",
    title: t2("Электропривод SF24-SR"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 20.0, "springReturn": true, "control": "Плавное", "signal": "2…10 В DC", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Управляющий сигнал"), value: "2…10 В DC" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "20", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "10", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Время пружинного возврата"), value: "<25 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "≈3000", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "64–65", edition: '2026' }, sourcePdfPage: 33,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sf24-srz",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SF24-SRZ",
    title: t2("Электропривод SF24-SRZ"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 20.0, "springReturn": true, "control": "Плавное", "signal": "0…10 В DC", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Управляющий сигнал"), value: "0…10 В DC" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "20", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "10", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "3", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Время пружинного возврата"), value: "<25 с при –20…+50 °С; <60 с" },
      { label: t2("Масса"), value: "≈3000", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "64–65", edition: '2026' }, sourcePdfPage: 33,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
];
