/** Каталожные приводы «НЕМАН», данные карточек 2026 года. */
import { t2, type Component } from '../model';
import { VALVE_CLASS_ID } from '../valve/class';

const CATALOG_FILE = 'HEMAH_Каталог основных видов_2026 [lUHZBf].pdf';

export const NEMAN_FIRE_COMPONENTS: Component[] = [
  {
    id: "cmp-neman-blf24-3",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLF24-3",
    title: t2("Электропривод BLF24-3"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 3.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "3", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<15 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "25...45с/90°" },
      { label: t2("Масса"), value: "≈1200", unit: "г" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "3,5", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "68–69", edition: '2026' }, sourcePdfPage: 35,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-blf230-3",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLF230-3",
    title: t2("Электропривод BLF230-3"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 3.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "3", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<15 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "25...45с/90°" },
      { label: t2("Масса"), value: "≈1200", unit: "г" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "3,5", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "68–69", edition: '2026' }, sourcePdfPage: 35,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-blf24-3-t",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLF24-3-T",
    title: t2("Электропривод BLF24-3-T"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 3.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "3", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<15 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "25...45с/90°" },
      { label: t2("Масса"), value: "≈1200", unit: "г" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "3,5", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "70–71", edition: '2026' }, sourcePdfPage: 36,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-blf230-3-t",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLF230-3-T",
    title: t2("Электропривод BLF230-3-T"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 3.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "3", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<15 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "25...45с/90°" },
      { label: t2("Масса"), value: "≈1200", unit: "г" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "3,5", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "70–71", edition: '2026' }, sourcePdfPage: 36,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-blf24-5",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLF24-5",
    title: t2("Электропривод BLF24-5"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 5.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<20 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<70с/90°" },
      { label: t2("Масса"), value: "≈2000", unit: "г" },
      { label: t2("Расчётная мощность"), value: "8", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "3", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "72–73", edition: '2026' }, sourcePdfPage: 37,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-blf230-5",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLF230-5",
    title: t2("Электропривод BLF230-5"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 5.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<20 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<70с/90°" },
      { label: t2("Масса"), value: "≈2000", unit: "г" },
      { label: t2("Расчётная мощность"), value: "8", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "3", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "72–73", edition: '2026' }, sourcePdfPage: 37,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-blf24-5-t",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLF24-5-T",
    title: t2("Электропривод BLF24-5-T"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 5.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<20 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<70с/90°" },
      { label: t2("Масса"), value: "≈2000", unit: "г" },
      { label: t2("Расчётная мощность"), value: "8", unit: "ВА" },
      { label: t2("Мощность при удержании"), value: "3", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "74–75", edition: '2026' }, sourcePdfPage: 38,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-blf230-5-t",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BLF230-5-T",
    title: t2("Электропривод BLF230-5-T"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 5.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<20 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<70с/90°" },
      { label: t2("Масса"), value: "≈2000", unit: "г" },
      { label: t2("Расчётная мощность"), value: "8", unit: "ВА" },
      { label: t2("Мощность при удержании"), value: "3", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "74–75", edition: '2026' }, sourcePdfPage: 38,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-bf24-10",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BF24-10",
    title: t2("Электропривод BF24-10"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<25 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<100с/90°" },
      { label: t2("Масса"), value: "≈2300", unit: "г" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "3", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "76–77", edition: '2026' }, sourcePdfPage: 39,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-bf230-10",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BF230-10",
    title: t2("Электропривод BF230-10"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 10.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<25 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<100с/90°" },
      { label: t2("Масса"), value: "≈2300", unit: "г" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "3", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "76–77", edition: '2026' }, sourcePdfPage: 39,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-bf24-10-t",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BF24-10-T",
    title: t2("Электропривод BF24-10-T"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<25 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<100с/90°" },
      { label: t2("Масса"), value: "≈2300", unit: "г" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "3", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "78–79", edition: '2026' }, sourcePdfPage: 40,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-bf230-10-t",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BF230-10-T",
    title: t2("Электропривод BF230-10-T"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 10.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Время пружинного возврата"), value: "<25 с" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<100с/90°" },
      { label: t2("Масса"), value: "≈2300", unit: "г" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "3", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "78–79", edition: '2026' }, sourcePdfPage: 40,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-bfg24-20",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BFG24-20",
    title: t2("Электропривод BFG24-20"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 20.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Масса"), value: "≈3200", unit: "г" },
      { label: t2("Время пружинного возврата"), value: "<30 c при –10…+50 °С; <60 с при –30...–10 °С" },
      { label: t2("Расчётная мощность"), value: "40", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "20", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "2,5", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "80–81", edition: '2026' }, sourcePdfPage: 41,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-bfg230-20",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BFG230-20",
    title: t2("Электропривод BFG230-20"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 20.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Масса"), value: "≈3200", unit: "г" },
      { label: t2("Время пружинного возврата"), value: "<30 c при –10…+50 °С; <60 с при –30...–10 °С" },
      { label: t2("Расчётная мощность"), value: "40", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "20", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "2,5", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "80–81", edition: '2026' }, sourcePdfPage: 41,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-bfg24-20-t",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BFG24-20-T",
    title: t2("Электропривод BFG24-20-T"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 20.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Масса"), value: "≈3200", unit: "г" },
      { label: t2("Время пружинного возврата"), value: "<30 c при –10…+50 °С; <60 с при –30...–10 °С" },
      { label: t2("Расчётная мощность"), value: "40", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "20", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "2,5", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "82–83", edition: '2026' }, sourcePdfPage: 42,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-bfg230-20-t",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "BFG230-20-T",
    title: t2("Электропривод BFG230-20-T"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 20.0, "springReturn": true, "control": "Открыто/закрыто", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Да" },
      { label: t2("Управление"), value: "Открыто/закрыто" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
            { label: t2("Температура хранения"), value: "–30...+60", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<30с/90°" },
      { label: t2("Масса"), value: "≈3200", unit: "г" },
      { label: t2("Время пружинного возврата"), value: "<30 c при –10…+50 °С; <60 с при –30...–10 °С" },
      { label: t2("Расчётная мощность"), value: "40", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "20", unit: "Вт" },
      { label: t2("Мощность при удержании"), value: "2,5", unit: "Вт" },
    ],
    catalog: { file: CATALOG_FILE, pages: "82–83", edition: '2026' }, sourcePdfPage: 42,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
];
