/** Каталожные приводы «НЕМАН», данные карточек 2026 года. */
import { t2, type Component } from '../model';
import { VALVE_CLASS_ID } from '../valve/class';

const CATALOG_FILE = 'HEMAH_Каталог основных видов_2026 [lUHZBf].pdf';

export const NEMAN_STANDARD_COMPONENTS: Component[] = [
  {
    id: "cmp-neman-lm230",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LM230",
    title: t2("Электропривод LM230"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 5.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "3", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "8–9", edition: '2026' }, sourcePdfPage: 5,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lm230-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LM230-S2",
    title: t2("Электропривод LM230-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 5.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "3", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "8–9", edition: '2026' }, sourcePdfPage: 5,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lm24",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LM24",
    title: t2("Электропривод LM24"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 5.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "3", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90" },
      { label: t2("Масса"), value: "≈800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "10–11", edition: '2026' }, sourcePdfPage: 6,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lm24-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LM24-S2",
    title: t2("Электропривод LM24-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 5.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "3", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90" },
      { label: t2("Масса"), value: "≈800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "10–11", edition: '2026' }, sourcePdfPage: 6,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lm230-sra",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LM230-SRA",
    title: t2("Электропривод LM230-SRA"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 5.0, "springReturn": false, "control": "Плавное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "12–13", edition: '2026' }, sourcePdfPage: 7,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lm230-sra-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LM230-SRA-S2",
    title: t2("Электропривод LM230-SRA-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 5.0, "springReturn": false, "control": "Плавное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "12–13", edition: '2026' }, sourcePdfPage: 7,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lm24-sra",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LM24-SRA",
    title: t2("Электропривод LM24-SRA"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 5.0, "springReturn": false, "control": "Плавное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "3", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "14–15", edition: '2026' }, sourcePdfPage: 8,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-lm24-sra-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "LM24-SRA-S2",
    title: t2("Электропривод LM24-SRA-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 5.0, "springReturn": false, "control": "Плавное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "5", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "7", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "3", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈800", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "14–15", edition: '2026' }, sourcePdfPage: 8,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nm230",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NM230",
    title: t2("Электропривод NM230"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 10.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈1100", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "16–17", edition: '2026' }, sourcePdfPage: 9,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nm230-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NM230-S2",
    title: t2("Электропривод NM230-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 10.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈1100", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "16–17", edition: '2026' }, sourcePdfPage: 9,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nm24",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NM24",
    title: t2("Электропривод NM24"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈1100", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "18–19", edition: '2026' }, sourcePdfPage: 10,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nm24-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NM24-S2",
    title: t2("Электропривод NM24-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈1100", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "18–19", edition: '2026' }, sourcePdfPage: 10,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nm230-sra",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NM230-SRA",
    title: t2("Электропривод NM230-SRA"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 10.0, "springReturn": false, "control": "Плавное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈1100", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "20–21", edition: '2026' }, sourcePdfPage: 11,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nm230-sra-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NM230-SRA-S2",
    title: t2("Электропривод NM230-SRA-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 10.0, "springReturn": false, "control": "Плавное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈1100", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "20–21", edition: '2026' }, sourcePdfPage: 11,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nm24-sra",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NM24-SRA",
    title: t2("Электропривод NM24-SRA"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": false, "control": "Плавное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈1100", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "22–23", edition: '2026' }, sourcePdfPage: 12,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-nm24-sra-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "NM24-SRA-S2",
    title: t2("Электропривод NM24-SRA-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 10.0, "springReturn": false, "control": "Плавное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "10", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<60с/90°" },
      { label: t2("Масса"), value: "≈1100", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "22–23", edition: '2026' }, sourcePdfPage: 12,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sm230",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SM230",
    title: t2("Электропривод SM230"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 20.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1400", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "24–25", edition: '2026' }, sourcePdfPage: 13,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sm230-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SM230-S2",
    title: t2("Электропривод SM230-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 20.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1400", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "24–25", edition: '2026' }, sourcePdfPage: 13,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sm24",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SM24",
    title: t2("Электропривод SM24"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 20.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1400", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "26–27", edition: '2026' }, sourcePdfPage: 14,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sm24-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SM24-S2",
    title: t2("Электропривод SM24-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 20.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1400", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "26–27", edition: '2026' }, sourcePdfPage: 14,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sm230-sra",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SM230-SRA",
    title: t2("Электропривод SM230-SRA"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 20.0, "springReturn": false, "control": "Плавное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1400", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "28–29", edition: '2026' }, sourcePdfPage: 15,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sm230-sra-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SM230-SRA-S2",
    title: t2("Электропривод SM230-SRA-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 20.0, "springReturn": false, "control": "Плавное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1400", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "28–29", edition: '2026' }, sourcePdfPage: 15,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sm24-sra",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SM24-SRA",
    title: t2("Электропривод SM24-SRA"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 20.0, "springReturn": false, "control": "Плавное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1400", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "30–31", edition: '2026' }, sourcePdfPage: 16,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-sm24-sra-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "SM24-SRA-S2",
    title: t2("Электропривод SM24-SRA-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 20.0, "springReturn": false, "control": "Плавное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "20", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "10", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "4,5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1400", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "30–31", edition: '2026' }, sourcePdfPage: 16,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-gm230",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "GM230",
    title: t2("Электропривод GM230"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 40.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "40", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "12", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1500", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "32–33", edition: '2026' }, sourcePdfPage: 17,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-gm230-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "GM230-S2",
    title: t2("Электропривод GM230-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 40.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "40", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "12", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1500", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "32–33", edition: '2026' }, sourcePdfPage: 17,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-gm24",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "GM24",
    title: t2("Электропривод GM24"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 40.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "40", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "12", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1500", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "34–35", edition: '2026' }, sourcePdfPage: 18,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-gm24-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "GM24-S2",
    title: t2("Электропривод GM24-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 40.0, "springReturn": false, "control": "Открыто/закрыто; трёхпозиционное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "40", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Открыто/закрыто; трёхпозиционное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "12", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1500", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "34–35", edition: '2026' }, sourcePdfPage: 18,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-gm230-sra",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "GM230-SRA",
    title: t2("Электропривод GM230-SRA"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 40.0, "springReturn": false, "control": "Плавное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "40", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "12", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1500", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "36–37", edition: '2026' }, sourcePdfPage: 19,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-gm230-sra-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "GM230-SRA-S2",
    title: t2("Электропривод GM230-SRA-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 230, "supplyType": "AC", "torqueNm": 40.0, "springReturn": false, "control": "Плавное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "230", unit: "В AC" },
      { label: t2("Крутящий момент"), value: "40", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "12", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1500", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "36–37", edition: '2026' }, sourcePdfPage: 19,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-gm24-sra",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "GM24-SRA",
    title: t2("Электропривод GM24-SRA"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 40.0, "springReturn": false, "control": "Плавное", "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "40", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "12", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1500", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "38–39", edition: '2026' }, sourcePdfPage: 20,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
  {
    id: "cmp-neman-gm24-sra-s2",
    classId: VALVE_CLASS_ID,
    kind: "actuator",
    code: "GM24-SRA-S2",
    title: t2("Электропривод GM24-SRA-S2"), manufacturer: "НЕМАН",
    facts: {"voltage": 24, "supplyType": "AC/DC", "torqueNm": 40.0, "springReturn": false, "control": "Плавное", "auxSwitches": 2, "ip": "IP54", "workTemperature": "–30...+50 °C"},
    specs: [

      { label: t2("Номинальное напряжение"), value: "24", unit: "В AC/DC" },
      { label: t2("Крутящий момент"), value: "40", unit: "Н·м" },
      { label: t2("Пружинный возврат"), value: "Нет" },
      { label: t2("Управление"), value: "Плавное" },
      { label: t2("Вспомогательные переключатели"), value: "2" },
      { label: t2("Степень защиты корпуса"), value: "IP54" },
      { label: t2("Температура окружающей среды"), value: "–30...+50", unit: "°C" },
      { label: t2("Расчётная мощность"), value: "12", unit: "ВА" },
      { label: t2("Мощность при работе двигателя"), value: "5", unit: "Вт" },
      { label: t2("Мощность в состоянии покоя"), value: "1", unit: "Вт" },
            { label: t2("Температура хранения"), value: "–30...+80", unit: "°C" },
      { label: t2("Время поворота двигателя"), value: "<150с/90°" },
      { label: t2("Масса"), value: "≈1500", unit: "г" },
    ],
    catalog: { file: CATALOG_FILE, pages: "38–39", edition: '2026' }, sourcePdfPage: 20,
    status: 'partial', todo: ['Проверить мощность, времена и массу по изображению карточки', 'Добавлять применяемость только по подтверждённому источнику'],
  },
];
