'use strict';
const $=id=>document.getElementById(id);
const busyDisabled=new WeakMap();
let state={unlocked:false},tab='licenses',request=null,selected=new Set(),historySelected=new Set(),historyPage=0,lastRevocation='',busy=false,setupFolderSelected=false,wizardStage='';
const titles={licenses:'Лицензии сотрудников',updates:'Обновления Flux',keys:'Ключи и резервные копии',login:'Подключение к компании'};
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';$('notice').hidden=!text;}
function textNode(tag,text,className=''){const el=document.createElement(tag);el.textContent=text;if(className)el.className=className;return el;}
function resetPasswords(){document.querySelectorAll('input[type=password],input[type=text][data-password-field]').forEach(el=>el.value='');$('capsLockHelp').hidden=true;document.querySelectorAll('[data-toggle-password]').forEach(button=>{const input=$(button.dataset.togglePassword);input.type='password';button.textContent='Показать';button.setAttribute('aria-pressed','false');button.setAttribute('aria-label',button.dataset.showLabel);});}
async function action(name,args={},success=''){
  if(!window.owner)throw new Error('Откройте программу через Electron: интерфейс без защищённого моста недоступен.');
  if(busy&&name!=='cancel')return null;
  busy=name!=='cancel';toggleBusy();
  try{const result=await window.owner.call(name,args);if(!result.ok)throw new Error(result.error);if(success&&!result.value?.canceled)notice(success);return result.value;}
  catch(e){const message=e.message||'Операция не выполнена.';const field=name==='setup'?'setupError':name==='verifySetup'?'verifyError':'';if(field){$(field).textContent=message;$(field).hidden=false;}notice(message,true);return null;}
  finally{busy=false;toggleBusy();}
}
function toggleBusy(){document.querySelectorAll('button,input,select,textarea').forEach(el=>{if(el.id==='cancel')return;if(el.dataset.tab){el.disabled=busy||!state.unlocked||!!wizardStage;return;}if(busy){if(!busyDisabled.has(el))busyDisabled.set(el,el.disabled);el.disabled=true;}else if(busyDisabled.has(el)){el.disabled=busyDisabled.get(el);busyDisabled.delete(el);}});if(!busy){$('copyIssued').disabled=!$('issuedCode').value;$('openFlux').disabled=!state.connected;$('disconnect').disabled=!state.connected;$('unlock').disabled=!state.vaultExists;$('publicExport').disabled=state.kind==='backup';$('publicApply').disabled=state.kind==='backup';$('issue').disabled=state.kind==='backup'||!selected.size;$('publish').disabled=state.kind==='backup'||!state.connected||!state.exe;$('signUpdate').disabled=state.kind==='backup'||!state.exe;$('chooseExe').disabled=state.kind==='backup';$('revoke').disabled=state.kind==='backup'||!historySelected.size;$('changePasswordButton').disabled=!!state.backupSession;$('create').disabled=$('setupFields').hidden||!setupFolderSelected;}}
async function refresh(){const next=await action('state');if(next){state=next;render();}}
function render(){
  $('locked').hidden=state.unlocked&&!wizardStage;$('vaultBadge').textContent=state.unlocked?(state.kind==='backup'?'Аварийный вход':'Хранилище открыто'):'Хранилище закрыто';
  const connectionName='Общая база MariaDB / MySQL';
  $('connectionLabel').textContent=state.connected?connectionName:'База не подключена';$('loginDetails').textContent=state.connected?`${connectionName} · ${state.user?.name||'Владелец'} · OWNER`:'Нет подключения';
  const stageText={edit:['Создание ключей','Создайте хранилище владельца','Задайте один пароль и выберите папку для резервных копий.'],verify:['Проверка пароля','Проверьте созданное хранилище','Подтвердите пароль, чтобы проверить основной файл и резервные копии.'],complete:['Настройка завершена','Хранилище готово','Передайте сборщику Flux только открытый файл flux-public-keys.json.']}[wizardStage];
  $('vaultIntro').textContent=stageText?.[0]||(state.vaultExists?'Вход владельца':'Первый запуск');$('vaultTitle').textContent=stageText?.[1]||(state.vaultExists?'Откройте хранилище':'Добро пожаловать в Flux Owner');$('vaultDescription').textContent=stageText?.[2]||(state.vaultExists?'Введите один пароль, чтобы открыть хранилище на этом компьютере.':'Создайте хранилище владельца. Закрытые ключи останутся на этом компьютере.');$('vaultLocation').hidden=!state.vaultExists;$('vaultLocation').textContent=state.vaultPath?`Файл на этом компьютере: ${state.vaultPath}`:'';$('existingVaultEntry').hidden=!state.vaultExists;$('startSetup').textContent=state.vaultExists?'Создать новые ключи':'Создать хранилище';$('startSetup').className=state.vaultExists?'secondary':'';$('replaceWarning').hidden=!state.vaultExists;$('previousVaultNote').hidden=!state.previousVaultPath;$('previousVaultNote').textContent=state.previousVaultPath?`Старая копия хранилища сохранена: ${state.previousVaultPath}`:'';$('setupKitPath').textContent=state.setupKitPath?`Комплект настройки: ${state.setupKitPath}`:'';$('publicFilePath').textContent=state.publicFilePath?`Открытый JSON: ${state.publicFilePath}`:'';
  $('lock').hidden=!state.unlocked||!!wizardStage;document.querySelectorAll('.tab').forEach(el=>el.hidden=!state.unlocked||!!wizardStage||el.id!==tab);document.querySelectorAll('[data-tab]').forEach(el=>{el.disabled=busy||!state.unlocked||!!wizardStage;el.classList.toggle('active',state.unlocked&&!wizardStage&&el.dataset.tab===tab);});$('pageTitle').textContent=state.unlocked&&!wizardStage?titles[tab]:'Ключи владельца';$('versionLabel').textContent=state.version?`Версия ${state.version}`:'';
  $('recoveryMethods').hidden=!!wizardStage;$('loginFields').hidden=!!wizardStage;$('setupFields').hidden=wizardStage!=='edit';$('verifyFields').hidden=wizardStage!=='verify';$('setupComplete').hidden=wizardStage!=='complete';
  renderKeys();renderHistory();renderUpdates();
  $('exeDetails').textContent=state.exe?`${state.exe.name}\n${(state.exe.size/1024/1024).toFixed(1)} МБ\nSHA-256: ${state.exe.sha256}`:'Файл не выбран';toggleBusy();
}
function renderKeys(){const box=$('publicKeys');box.replaceChildren();const names={license:'Подпись лицензий и отзыва',update:'Подпись обновлений',owner:'Вход владельца',ownerBackup:'Запасной вход владельца'};for(const [purpose,hex]of Object.entries({...state.publicKeys,ownerBackup:state.backupOwnerPublic})){if(!hex)continue;const row=textNode('div','','key');row.append(textNode('strong',names[purpose]||purpose),textNode('code',hex));const btn=textNode('button','Скопировать','secondary');btn.addEventListener('click',()=>action('copy',{text:hex},'Открытый ключ скопирован.'));row.append(btn);box.append(row);}}
function renderPeople(){if(!request)return;const filter=$('peopleFilter').value.toLowerCase(),shown=request.people.filter(p=>`${p.login} ${p.name}`.toLowerCase().includes(filter));$('peopleCount').textContent=`${selected.size} из ${request.people.length}`;const box=$('people');box.replaceChildren();for(const p of shown.slice(0,200)){const label=textNode('label','','person'),check=document.createElement('input');check.type='checkbox';check.checked=selected.has(p.login);check.setAttribute('aria-label',`Выбрать ${p.name||p.login}`);check.addEventListener('change',()=>{check.checked?selected.add(p.login):selected.delete(p.login);$('peopleCount').textContent=`${selected.size} из ${request.people.length}`;toggleBusy();});const text=document.createElement('span');text.append(textNode('strong',p.name||p.login),textNode('small',p.login));label.append(check,text);box.append(label);}if(shown.length>200)box.append(textNode('p',`Показаны первые 200 из ${shown.length}. Уточните поиск. Выбор остальных сотрудников сохранён.`,'muted'));if(!shown.length)box.append(textNode('p','Сотрудники не найдены.','muted'));toggleBusy();}
function setExpiry(){if($('duration').value==='custom')return;const date=new Date(),day=date.getDate();date.setDate(1);date.setMonth(date.getMonth()+Number($('duration').value));date.setDate(Math.min(day,new Date(date.getFullYear(),date.getMonth()+1,0).getDate()));$('expiration').value=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');}
function displayDate(ms){return new Date(ms).toLocaleDateString('ru-RU');}
function revoked(p){return (state.revocations||[]).some(r=>r.inst===p.inst&&r.ids.includes(p.id));}
function renderHistory(){const filter=$('historyFilter').value.toLowerCase(),rows=(state.licenses||[]).filter(p=>`${p.org} ${p.inst} ${p.logins.join(' ')}`.toLowerCase().includes(filter)).slice().reverse();const pages=Math.max(1,Math.ceil(rows.length/25));historyPage=Math.min(historyPage,pages-1);const body=$('licenseRows');body.replaceChildren();for(const p of rows.slice(historyPage*25,(historyPage+1)*25)){const tr=document.createElement('tr'),pick=document.createElement('td'),check=document.createElement('input');check.type='checkbox';check.checked=historySelected.has(p.id);check.setAttribute('aria-label',`Выбрать лицензию ${p.id}`);check.addEventListener('change',()=>{check.checked?historySelected.add(p.id):historySelected.delete(p.id);toggleBusy();});pick.append(check);const org=textNode('td',p.org||'Компания');org.append(textNode('small',p.inst));const people=textNode('td',p.logins.join(', ')),expiry=textNode('td',displayDate(p.exp));expiry.append(textNode('small',revoked(p)?'Отозвана':p.exp<=Date.now()?'Истекла':`${Math.ceil((p.exp-Date.now())/86400000)} дн.`));const key=textNode('td',p.id),copy=textNode('button','Копировать','secondary small');copy.addEventListener('click',()=>action('copy',{text:p.code},'Ключ лицензии скопирован.'));key.append(document.createElement('br'),copy);tr.append(pick,org,people,expiry,key);body.append(tr);}if(!rows.length){const tr=document.createElement('tr'),td=textNode('td','Выданных лицензий пока нет.');td.colSpan=5;tr.append(td);body.append(tr);}$('historyPage').textContent=`Страница ${historyPage+1} из ${pages} · ${rows.length} лицензий`;$('historyPrev').disabled=historyPage===0;$('historyNext').disabled=historyPage>=pages-1;}
function renderUpdates(){const box=$('updateRows');box.replaceChildren();for(const p of (state.updates||[]).slice().reverse().slice(0,50)){const row=textNode('div','','update-entry');row.append(textNode('strong',`${p.version} · ${p.published?'Опубликована':'Подписана'}`),textNode('p',`${displayDate(p.iat)} · ${p.name} · ${(p.size/1024/1024).toFixed(1)} МБ`,'muted'));const buttons=textNode('div','','row'),copy=textNode('button','Копировать подпись','secondary small');copy.addEventListener('click',()=>action('copy',{text:p.signature},'Подпись скопирована.'));buttons.append(copy);if(p.published){const remove=textNode('button','Отозвать выпуск','secondary small');remove.disabled=!state.connected||state.server!==p.server;remove.addEventListener('click',()=>action('withdrawUpdate',{version:p.version},'Выпуск отозван в общей БД.'));buttons.append(remove);}row.append(buttons);box.append(row);}if(!state.updates?.length)box.append(textNode('p','Подписанных выпусков пока нет.','muted'));}
function on(id,handler){$(id).addEventListener('click',()=>Promise.resolve(handler()).catch(e=>notice(e.message,true)));}
document.querySelectorAll('[data-toggle-password]').forEach(button=>{const input=$(button.dataset.togglePassword);button.dataset.showLabel=button.getAttribute('aria-label');button.addEventListener('click',()=>{const shown=input.type==='text';input.type=shown?'password':'text';button.textContent=shown?'Показать':'Скрыть';button.setAttribute('aria-pressed',String(!shown));button.setAttribute('aria-label',shown?button.dataset.showLabel:button.dataset.showLabel.replace('Показать','Скрыть'));});});
document.querySelectorAll('input[type=password]').forEach(input=>{const update=event=>{$('capsLockHelp').hidden=!event.getModifierState('CapsLock');};input.addEventListener('keydown',update);input.addEventListener('keyup',update);input.addEventListener('blur',()=>{$('capsLockHelp').hidden=true;});});
document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>{tab=btn.dataset.tab;document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el===btn));render();}));
on('unlock',async()=>{const next=await action('unlock',{password:$('password').value},'Хранилище разблокировано.');resetPasswords();if(next){state=next;wizardStage=next.setupKitPath&&!next.setupVerified?'verify':'';render();if(wizardStage==='verify')$('verifyPassword').focus();}});
on('openBackup',async()=>{const next=await action('openBackup',{password:$('openBackupPassword').value},'Запасной ключ открыт для входа. Основное хранилище не изменено.');resetPasswords();if(next&&!next.canceled){state=next;wizardStage='';tab='login';document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===tab));render();$('serverUrl').focus();}});
on('startSetup',()=>{wizardStage='edit';setupFolderSelected=false;$('setupFolderLabel').textContent='Папка не выбрана';$('setupError').hidden=true;render();});
on('cancelSetup',()=>{wizardStage='';resetPasswords();render();});
on('chooseSetupFolder',async()=>{const result=await action('chooseSetupFolder',{});if(result&&!result.canceled){setupFolderSelected=true;$('setupFolderLabel').textContent=result.folderPath||'Папка выбрана';$('setupFolderLabel').title=result.folderPath||'';$('create').disabled=false;}});
on('create',async()=>{const password=$('setupPassword').value,confirmPassword=$('setupConfirm').value;$('setupError').hidden=true;let error='';if(!setupFolderSelected)error='Сначала выберите папку для комплекта резервных копий.';else if(password.length<12)error='Пароль должен содержать не менее 12 символов.';else if(password!==confirmPassword)error='Пароли при повторном вводе не совпадают.';if(error){$('setupError').textContent=error;$('setupError').hidden=false;return;}const next=await action('setup',{password,confirmPassword,replaceExisting:!!state.vaultExists},'Ключи созданы. Проверьте хранилище повторным вводом пароля.');resetPasswords();if(next&&!next.canceled){state=next;wizardStage='verify';render();$('verifyPassword').focus();}});
on('verifySetup',async()=>{const password=$('verifyPassword').value;$('verifyError').hidden=true;if(!password){$('verifyError').textContent='Введите пароль для проверки созданных файлов.';$('verifyError').hidden=false;return;}const next=await action('verifySetup',{password},'Основное хранилище и резервные копии успешно проверены.');resetPasswords();if(next&&next.setupVerified){state=next;wizardStage='complete';render();}});
on('showSetupFolder',()=>action('showSetupFolder',{},'Папка с комплектом настройки открыта.'));on('exportSetupPublic',()=>action('publicExport',{},'Экспортирован flux-public-keys.json. Передайте сборщику только этот файл.'));
on('enterOwner',()=>{wizardStage='';tab='licenses';render();});
on('import',async()=>{if($('newPassword').value.length<12||$('newPassword').value!==$('newPasswordConfirm').value)return notice('Повторите новый пароль: значения должны совпадать и содержать не менее 12 символов.',true);const next=await action('import',{importPassword:$('importPassword').value,password:$('newPassword').value},'Хранилище импортировано.');resetPasswords();if(next&&!next.canceled){state=next;wizardStage='';render();}});
on('lock',async()=>{await action('lock');wizardStage='';state={...state,unlocked:false,connected:false,publicKeys:{},licenses:[],updates:[],revocations:[],exe:null};request=null;selected.clear();historySelected.clear();$('requestCode').value='';$('issuedCode').value='';$('requestDetails').hidden=true;resetPasswords();render();});
on('parseRequest',async()=>{const parsed=await action('request',{code:$('requestCode').value});if(!parsed)return;request=parsed;selected=new Set(parsed.people.map(p=>p.login));$('requestDetails').hidden=false;$('installation').textContent=`Установка: ${parsed.inst}`;$('company').value=parsed.org;renderPeople();setExpiry();notice('Запрос прочитан. Проверьте компанию, сотрудников и срок.');});
$('peopleFilter').addEventListener('input',renderPeople);on('allPeople',()=>{if(request)selected=new Set(request.people.map(p=>p.login));renderPeople();});on('nonePeople',()=>{selected.clear();renderPeople();});$('duration').addEventListener('change',setExpiry);$('expiration').addEventListener('input',()=>$('duration').value='custom');
on('issue',async()=>{const date=$('expiration').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return notice('Выберите дату окончания.',true);const exp=new Date(`${date}T23:59:59.999`).getTime();const issued=await action('issue',{code:$('requestCode').value,logins:[...selected],org:$('company').value,expiresAt:exp},'Лицензия выпущена и сохранена в зашифрованном реестре.');if(issued){$('issuedCode').value=issued.code;lastRevocation='';$('publishRevocation').hidden=true;await refresh();}});
on('copyIssued',()=>action('copy',{text:$('issuedCode').value},'Код скопирован.'));
on('revoke',async()=>{const rows=(state.licenses||[]).filter(p=>historySelected.has(p.id));const insts=new Set(rows.map(p=>p.inst));if(insts.size!==1)return notice('Для одного списка отзыва выберите лицензии одной установки.',true);const issued=await action('revoke',{inst:rows[0].inst,ids:rows.map(p=>p.id)},'Список отзыва подписан. Передайте его администратору или отправьте в общую БД.');if(issued&&!issued.canceled){lastRevocation=issued.code;$('issuedCode').value=issued.code;$('publishRevocation').hidden=false;historySelected.clear();await refresh();}});
on('publishRevocation',()=>action('publishRevocation',{code:lastRevocation},'Общая БД применила список отзыва.'));
$('historyFilter').addEventListener('input',()=>{historyPage=0;renderHistory();});on('historyPrev',()=>{historyPage=Math.max(0,historyPage-1);renderHistory();});on('historyNext',()=>{historyPage++;renderHistory();});
on('chooseExe',async()=>{const next=await action('chooseExe');if(next&&!next.canceled){state=next;render();notice('EXE проверен. Введите версию и описание изменений.');}});on('signUpdate',async()=>{const result=await action('signUpdate',{version:$('version').value.trim()},'Подпись сохранена.');if(result&&!result.canceled)await refresh();});on('publish',async()=>{const result=await action('publish',{version:$('version').value.trim(),changelog:$('changelog').value},'Обновление опубликовано через БД.');if(result&&!result.canceled)await refresh();});
on('publicExport',()=>action('publicExport',{},'Открытые ключи экспортированы. Передайте flux-public-keys.json сборщику Flux; файл .flux-owner оставьте у себя.'));
on('publicApply',()=>action('publicApply',{},'Открытые ключи закреплены. Пересоберите Flux и установите первую версию вручную.'));
on('export',async()=>{await action('export',{password:$('exportPassword').value},'Резервная копия сохранена.');resetPasswords();});on('changePasswordButton',async()=>{if($('changePassword').value!==$('confirmChange').value)return notice('Пароли не совпадают.',true);await action('changePassword',{password:$('changePassword').value},'Пароль локального хранилища изменён.');resetPasswords();});
on('connect',async()=>{const next=await action('connect',{server:$('serverUrl').value.trim()},'Вход владельца подтверждён.');if(next){$('serverUrl').value='';state=next;render();}});on('disconnect',async()=>{const next=await action('disconnect',{},'Подключение к общей БД закрыто.');if(next){state=next;render();}});on('openFlux',()=>action('openFlux'));on('cancel',()=>action('cancel',{},'Операция отменяется. Уже завершённая публикация сохраняется.'));
document.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.isComposing){if(event.target.id==='password'){event.preventDefault();$('unlock').click();}else if(event.target.id==='verifyPassword'){event.preventDefault();$('verifySetup').click();}}if(event.key==='Escape'&&wizardStage==='edit'&&!busy){event.preventDefault();$('cancelSetup').click();}});
if(window.owner){window.owner.onDisconnected?.(()=>{state={...state,connected:false,server:'',user:null};render();notice('Локальный обработчик Flux завершился. Проверьте доступность общей базы и подключитесь снова.',true);});window.owner.onProgress(p=>{$('progress').hidden=!p.phase;$('progressLabel').textContent=p.phase;$('progressBar').value=p.total?Math.round(p.current/p.total*100):0;});window.owner.onLocked(()=>{wizardStage='';resetPasswords();request=null;selected.clear();historySelected.clear();$('requestDetails').hidden=true;$('requestCode').value='';$('issuedCode').value='';lastRevocation='';notice('Хранилище заблокировано.');refresh();});refresh();}else notice('Защищённый мост не найден. Запустите Flux Владелец через Electron.',true);
setExpiry();
