'use strict';
const $=id=>document.getElementById(id);
const busyDisabled=new WeakMap();
let state={unlocked:false},tab='licenses',request=null,selected=new Set(),historySelected=new Set(),historyPage=0,lastRevocation='',busy=false;
const titles={licenses:'Лицензии сотрудников',updates:'Обновления Flux',keys:'Ключи и резервные копии',login:'Сервер компании'};
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';$('notice').hidden=!text;}
function textNode(tag,text,className=''){const el=document.createElement(tag);el.textContent=text;if(className)el.className=className;return el;}
function resetPasswords(){document.querySelectorAll('input[type=password],input[type=text][data-password-field]').forEach(el=>el.value='');$('capsLockHelp').hidden=true;document.querySelectorAll('[data-toggle-password]').forEach(button=>{const input=$(button.dataset.togglePassword);input.type='password';button.textContent='Показать';button.setAttribute('aria-pressed','false');button.setAttribute('aria-label',button.dataset.showLabel);});}
async function action(name,args={},success=''){
  if(!window.owner)throw new Error('Откройте программу через Electron: интерфейс без защищённого моста недоступен.');
  if(busy&&name!=='cancel')return null;
  busy=name!=='cancel';toggleBusy();
  try{const result=await window.owner.call(name,args);if(!result.ok)throw new Error(result.error);if(success&&!result.value?.canceled)notice(success);return result.value;}
  catch(e){notice(e.message||'Операция не выполнена.',true);return null;}
  finally{busy=false;toggleBusy();}
}
function toggleBusy(){document.querySelectorAll('button').forEach(el=>{if(el.id==='cancel'||el.dataset.tab)return;if(busy){if(!busyDisabled.has(el))busyDisabled.set(el,el.disabled);el.disabled=true;}else if(busyDisabled.has(el)){el.disabled=busyDisabled.get(el);busyDisabled.delete(el);}});if(!busy){$('copyIssued').disabled=!$('issuedCode').value;$('openFlux').disabled=!state.connected;$('disconnect').disabled=!state.connected;$('unlock').disabled=!state.vaultExists;$('publicExport').disabled=state.kind==='backup';$('publicApply').disabled=state.kind==='backup';$('issue').disabled=state.kind==='backup'||!selected.size;$('publish').disabled=state.kind==='backup'||!state.connected||!state.exe;$('signUpdate').disabled=state.kind==='backup'||!state.exe;$('chooseExe').disabled=state.kind==='backup';$('revoke').disabled=state.kind==='backup'||!historySelected.size;$('changePasswordButton').disabled=!!state.backupSession;}}
async function refresh(){const next=await action('state');if(next){state=next;render();}}
function render(){
  $('locked').hidden=state.unlocked;$('vaultBadge').textContent=state.unlocked?(state.kind==='backup'?'Запасной ключ владельца':'Хранилище открыто'):'Хранилище закрыто';
  $('createFields').hidden=!!state.vaultExists;$('connectionLabel').textContent=state.connected?state.server:'Сервер не подключён';$('loginDetails').textContent=state.connected?`${state.server} · ${state.user?.name||'Владелец'} · OWNER`:'Нет подключения';
  $('vaultIntro').textContent=state.vaultExists?'Вход владельца':'Первый запуск';$('vaultTitle').textContent=state.vaultExists?'Откройте хранилище на этом компьютере':'Создайте локальное хранилище владельца';$('vaultLocation').hidden=!state.vaultExists;$('vaultLocation').textContent=state.vaultPath?`Основной файл: ${state.vaultPath}`:'';$('passwordHelp').textContent=state.vaultExists?'Введите пароль основного хранилища. Для запасного файла используйте «Войти с запасным ключом».':'Не менее 12 символов. Это пароль для ключей на этом компьютере.';$('password').autocomplete=state.vaultExists?'off':'new-password';
  $('lock').hidden=!state.unlocked;document.querySelectorAll('.tab').forEach(el=>el.hidden=!state.unlocked||el.id!==tab);$('pageTitle').textContent=state.unlocked?titles[tab]:'Ключи владельца';
  renderKeys();renderHistory();renderUpdates();
  $('exeDetails').textContent=state.exe?`${state.exe.name}\n${(state.exe.size/1024/1024).toFixed(1)} МБ\nSHA-256: ${state.exe.sha256}`:'Файл не выбран';toggleBusy();
}
function renderKeys(){const box=$('publicKeys');box.replaceChildren();const names={license:'Подпись лицензий и отзыва',update:'Подпись обновлений',owner:'Вход владельца',ownerBackup:'Запасной вход владельца'};for(const [purpose,hex]of Object.entries({...state.publicKeys,ownerBackup:state.backupOwnerPublic})){if(!hex)continue;const row=textNode('div','','key');row.append(textNode('strong',names[purpose]||purpose),textNode('code',hex));const btn=textNode('button','Скопировать','secondary');btn.addEventListener('click',()=>action('copy',{text:hex},'Открытый ключ скопирован.'));row.append(btn);box.append(row);}}
function renderPeople(){if(!request)return;const filter=$('peopleFilter').value.toLowerCase(),shown=request.people.filter(p=>`${p.login} ${p.name}`.toLowerCase().includes(filter));$('peopleCount').textContent=`${selected.size} из ${request.people.length}`;const box=$('people');box.replaceChildren();for(const p of shown.slice(0,200)){const label=textNode('label','','person'),check=document.createElement('input');check.type='checkbox';check.checked=selected.has(p.login);check.setAttribute('aria-label',`Выбрать ${p.name||p.login}`);check.addEventListener('change',()=>{check.checked?selected.add(p.login):selected.delete(p.login);$('peopleCount').textContent=`${selected.size} из ${request.people.length}`;toggleBusy();});const text=document.createElement('span');text.append(textNode('strong',p.name||p.login),textNode('small',p.login));label.append(check,text);box.append(label);}if(shown.length>200)box.append(textNode('p',`Показаны первые 200 из ${shown.length}. Уточните поиск. Выбор остальных сотрудников сохранён.`,'muted'));if(!shown.length)box.append(textNode('p','Сотрудники не найдены.','muted'));toggleBusy();}
function setExpiry(){if($('duration').value==='custom')return;const date=new Date(),day=date.getDate();date.setDate(1);date.setMonth(date.getMonth()+Number($('duration').value));date.setDate(Math.min(day,new Date(date.getFullYear(),date.getMonth()+1,0).getDate()));$('expiration').value=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');}
function displayDate(ms){return new Date(ms).toLocaleDateString('ru-RU');}
function revoked(p){return (state.revocations||[]).some(r=>r.inst===p.inst&&r.ids.includes(p.id));}
function renderHistory(){const filter=$('historyFilter').value.toLowerCase(),rows=(state.licenses||[]).filter(p=>`${p.org} ${p.inst} ${p.logins.join(' ')}`.toLowerCase().includes(filter)).slice().reverse();const pages=Math.max(1,Math.ceil(rows.length/25));historyPage=Math.min(historyPage,pages-1);const body=$('licenseRows');body.replaceChildren();for(const p of rows.slice(historyPage*25,(historyPage+1)*25)){const tr=document.createElement('tr'),pick=document.createElement('td'),check=document.createElement('input');check.type='checkbox';check.checked=historySelected.has(p.id);check.setAttribute('aria-label',`Выбрать лицензию ${p.id}`);check.addEventListener('change',()=>{check.checked?historySelected.add(p.id):historySelected.delete(p.id);toggleBusy();});pick.append(check);const org=textNode('td',p.org||'Компания');org.append(textNode('small',p.inst));const people=textNode('td',p.logins.join(', ')),expiry=textNode('td',displayDate(p.exp));expiry.append(textNode('small',revoked(p)?'Отозвана':p.exp<=Date.now()?'Истекла':`${Math.ceil((p.exp-Date.now())/86400000)} дн.`));const key=textNode('td',p.id),copy=textNode('button','Копировать','secondary small');copy.addEventListener('click',()=>action('copy',{text:p.code},'Ключ лицензии скопирован.'));key.append(document.createElement('br'),copy);tr.append(pick,org,people,expiry,key);body.append(tr);}if(!rows.length){const tr=document.createElement('tr'),td=textNode('td','Выданных лицензий пока нет.');td.colSpan=5;tr.append(td);body.append(tr);}$('historyPage').textContent=`Страница ${historyPage+1} из ${pages} · ${rows.length} лицензий`;$('historyPrev').disabled=historyPage===0;$('historyNext').disabled=historyPage>=pages-1;}
function renderUpdates(){const box=$('updateRows');box.replaceChildren();for(const p of (state.updates||[]).slice().reverse().slice(0,50)){const row=textNode('div','','update-entry');row.append(textNode('strong',`${p.version} · ${p.published?'Опубликована':'Подписана'}`),textNode('p',`${displayDate(p.iat)} · ${p.name} · ${(p.size/1024/1024).toFixed(1)} МБ`,'muted'));if(p.server)row.append(textNode('p',p.server,'muted break'));const buttons=textNode('div','','row'),copy=textNode('button','Копировать подпись','secondary small');copy.addEventListener('click',()=>action('copy',{text:p.signature},'Подпись скопирована.'));buttons.append(copy);if(p.published){const remove=textNode('button','Отозвать выпуск','secondary small');remove.disabled=!state.connected||state.server!==p.server;remove.addEventListener('click',()=>action('withdrawUpdate',{version:p.version},'Выпуск отозван на подключённом сервере.'));buttons.append(remove);}row.append(buttons);box.append(row);}if(!state.updates?.length)box.append(textNode('p','Подписанных выпусков пока нет.','muted'));}
function on(id,handler){$(id).addEventListener('click',()=>Promise.resolve(handler()).catch(e=>notice(e.message,true)));}
document.querySelectorAll('[data-toggle-password]').forEach(button=>{const input=$(button.dataset.togglePassword);button.dataset.showLabel=button.getAttribute('aria-label');button.addEventListener('click',()=>{const shown=input.type==='text';input.type=shown?'password':'text';button.textContent=shown?'Показать':'Скрыть';button.setAttribute('aria-pressed',String(!shown));button.setAttribute('aria-label',shown?button.dataset.showLabel:button.dataset.showLabel.replace('Показать','Скрыть'));});});
document.querySelectorAll('input[type=password]').forEach(input=>{const update=event=>{$('capsLockHelp').hidden=!event.getModifierState('CapsLock');};input.addEventListener('keydown',update);input.addEventListener('keyup',update);input.addEventListener('blur',()=>{$('capsLockHelp').hidden=true;});});
document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>{tab=btn.dataset.tab;document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el===btn));render();}));
on('unlock',async()=>{const next=await action('unlock',{password:$('password').value},'Хранилище разблокировано.');resetPasswords();if(next){state=next;render();}});
on('openBackup',async()=>{const next=await action('openBackup',{password:$('openBackupPassword').value},'Запасной ключ открыт для входа. Основное хранилище не изменено.');resetPasswords();if(next&&!next.canceled){state=next;tab='login';document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===tab));render();$('serverUrl').focus();}});
on('create',async()=>{if($('password').value!==$('confirmPassword').value||$('backupPassword').value!==$('confirmBackup').value)return notice('Пароли при повторном вводе не совпадают.',true);if($('password').value.length<12||$('backupPassword').value.length<12)return notice('Каждый пароль должен содержать не менее 12 символов.',true);if($('password').value===$('backupPassword').value)return notice('Для запасного ключа придумайте другой пароль.',true);const next=await action('create',{password:$('password').value,backupPassword:$('backupPassword').value},'Хранилище создано. Теперь экспортируйте открытые ключи для первоначальной сборки Flux.');resetPasswords();if(next&&!next.canceled){state=next;tab='keys';document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab==='keys'));render();$('publicExport').focus();}});
on('import',async()=>{const next=await action('import',{importPassword:$('importPassword').value,password:$('newPassword').value},'Хранилище импортировано.');resetPasswords();if(next&&!next.canceled){state=next;render();}});
on('lock',async()=>{await action('lock');state={...state,unlocked:false,connected:false,publicKeys:{},licenses:[],updates:[],revocations:[],exe:null};request=null;selected.clear();historySelected.clear();$('requestCode').value='';$('issuedCode').value='';$('requestDetails').hidden=true;render();});
on('parseRequest',async()=>{const parsed=await action('request',{code:$('requestCode').value});if(!parsed)return;request=parsed;selected=new Set(parsed.people.map(p=>p.login));$('requestDetails').hidden=false;$('installation').textContent=`Установка: ${parsed.inst}`;$('company').value=parsed.org;renderPeople();setExpiry();notice('Запрос прочитан. Проверьте компанию, сотрудников и срок.');});
$('peopleFilter').addEventListener('input',renderPeople);on('allPeople',()=>{if(request)selected=new Set(request.people.map(p=>p.login));renderPeople();});on('nonePeople',()=>{selected.clear();renderPeople();});$('duration').addEventListener('change',setExpiry);$('expiration').addEventListener('input',()=>$('duration').value='custom');
on('issue',async()=>{const date=$('expiration').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return notice('Выберите дату окончания.',true);const exp=new Date(`${date}T23:59:59.999`).getTime();const issued=await action('issue',{code:$('requestCode').value,logins:[...selected],org:$('company').value,expiresAt:exp},'Лицензия выпущена и сохранена в зашифрованном реестре.');if(issued){$('issuedCode').value=issued.code;lastRevocation='';$('publishRevocation').hidden=true;await refresh();}});
on('copyIssued',()=>action('copy',{text:$('issuedCode').value},'Код скопирован.'));
on('revoke',async()=>{const rows=(state.licenses||[]).filter(p=>historySelected.has(p.id));const insts=new Set(rows.map(p=>p.inst));if(insts.size!==1)return notice('Для одного списка отзыва выберите лицензии одной установки.',true);const issued=await action('revoke',{inst:rows[0].inst,ids:rows.map(p=>p.id)},'Список отзыва подписан. Передайте его администратору или выбранному серверу.');if(issued&&!issued.canceled){lastRevocation=issued.code;$('issuedCode').value=issued.code;$('publishRevocation').hidden=false;historySelected.clear();await refresh();}});
on('publishRevocation',()=>action('publishRevocation',{code:lastRevocation},'Сервер применил список отзыва.'));
$('historyFilter').addEventListener('input',()=>{historyPage=0;renderHistory();});on('historyPrev',()=>{historyPage=Math.max(0,historyPage-1);renderHistory();});on('historyNext',()=>{historyPage++;renderHistory();});
on('chooseExe',async()=>{const next=await action('chooseExe');if(next&&!next.canceled){state=next;render();notice('EXE проверен. Введите версию и описание изменений.');}});on('signUpdate',async()=>{const result=await action('signUpdate',{version:$('version').value.trim()},'Подпись сохранена.');if(result&&!result.canceled)await refresh();});on('publish',async()=>{const result=await action('publish',{version:$('version').value.trim(),changelog:$('changelog').value},'Обновление опубликовано через БД.');if(result&&!result.canceled)await refresh();});
on('publicExport',()=>action('publicExport',{},'Открытые ключи экспортированы. Передайте flux-public-keys.json сборщику Flux; файл .flux-owner оставьте у себя.'));
on('publicApply',()=>action('publicApply',{},'Открытые ключи закреплены. Пересоберите Flux и установите первую версию вручную.'));
on('export',async()=>{await action('export',{password:$('exportPassword').value},'Резервная копия сохранена.');resetPasswords();});on('changePasswordButton',async()=>{if($('changePassword').value!==$('confirmChange').value)return notice('Пароли не совпадают.',true);await action('changePassword',{password:$('changePassword').value},'Пароль локального хранилища изменён.');resetPasswords();});
on('connect',async()=>{const next=await action('connect',{server:$('serverUrl').value.trim()},'Вход владельца подтверждён.');if(next){state=next;render();}});on('disconnect',async()=>{const next=await action('disconnect',{},'Подключение закрыто.');if(next){state=next;render();}});on('openFlux',()=>action('openFlux'));on('cancel',()=>action('cancel',{},'Операция отменяется. Уже завершённая публикация сохраняется.'));
if(window.owner){window.owner.onProgress(p=>{$('progress').hidden=!p.phase;$('progressLabel').textContent=p.phase;$('progressBar').value=p.total?Math.round(p.current/p.total*100):0;});window.owner.onLocked(()=>{resetPasswords();request=null;selected.clear();historySelected.clear();$('requestDetails').hidden=true;$('requestCode').value='';$('issuedCode').value='';lastRevocation='';notice('Хранилище заблокировано.');refresh();});refresh();}else notice('Защищённый мост не найден. Запустите Flux Владелец через Electron.',true);
setExpiry();
