import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { publicHexOf, readLicense, signLicense, personLicense } from '../license/node/core';
import { signRevocations, readRevocations, acceptsRevocations } from '../license/node/revocation';

const owner = crypto.generateKeyPairSync('ed25519').privateKey;
const stranger = crypto.generateKeyPairSync('ed25519').privateKey;
const hex = publicHexOf(owner);
const now = 1_900_000_000_000;
let n = 0;
const check = (title: string, value: unknown) => { assert.ok(value, title); console.log('✓', title); n++; };
const code = signRevocations({ inst: 'A', ids: ['key-1'], iat: now, seq: 1 }, owner);
const one = readRevocations(code, hex)!;
check('подпись отзыва читается', one.ids[0] === 'key-1');
check('чужая подпись не принимается', !readRevocations(signRevocations({ inst: 'A', ids: ['key-1'], iat: now, seq: 1 }, stranger), hex));
check('чужая установка не принимается', !acceptsRevocations(one, null, 'B'));
check('первый список принимается', acceptsRevocations(one, null, 'A'));
check('повторный номер не проходит как новый выпуск', !acceptsRevocations(one, one, 'A'));
check('следующий накопительный список принимается', acceptsRevocations({ ...one, ids: ['key-1', 'key-2'], seq: 2 }, one, 'A'));
check('нельзя убрать ранее отозванный ключ', !acceptsRevocations({ ...one, ids: [], seq: 2 }, one, 'A'));
check('старое время не принимается', !acceptsRevocations({ ...one, seq: 2, iat: now - 1 }, one, 'A'));
const parts = code.split('.');
const body = JSON.parse(Buffer.from(parts[1], 'base64url').toString()); body.ids = [];
parts[1] = Buffer.from(JSON.stringify(body)).toString('base64url');
check('изменённое содержимое ломает подпись', !readRevocations(parts.join('.'), hex));
check('строка лицензии не считается списком отзыва', !readRevocations(signLicense({ inst: 'A', org: '', logins: ['Иванов'], iat: now, exp: now + 1000 }, owner), hex));
const unsigned = (payload: unknown) => { const signed = `FLUXREV1.${Buffer.from(JSON.stringify(payload)).toString('base64url')}`; return `${signed}.${crypto.sign(null, Buffer.from(signed), owner).toString('base64url')}`; };
check('подписанный, но неверный формат отклоняется', !readRevocations(unsigned({ ...one, seq: -1 }), hex));
check('перечень ограничен 10 тысячами ключей', !readRevocations(unsigned({ ...one, ids: Array.from({ length: 10001 }, (_, i) => String(i)) }), hex));
const license = readLicense(signLicense({ inst: 'A', org: '', logins: ['Иванов'], iat: now, exp: now + 1000 }, owner), hex)!;
check('отозванный единственный ключ не даёт доступ', personLicense('иванов', 'A', [license], now, new Set([license.id])).reason === 'revoked');
console.log(`${n} проверок пройдено`);
