import assert from 'node:assert/strict';
import { billiards, groupOfBall, initPool, resolvePoolShot, type PoolState } from '../play/games/billiards';
import { canPlaceCue, simulateShot, type ShotSimulation } from '../play/games/billiardsPhysics';
import { PLAY_GAMES } from '../play/features';
let checks = 0;
const check = (name: string, condition: boolean) => { assert.ok(condition, name); checks++; console.log('✓', name); };
const state = initPool('repeatable', ['alice', 'bob']);
const shot = { type: 'shot' as const, angle: 0, power: 1 };
check('в каталоге только собственные новые игры', PLAY_GAMES.some(game => game.id === 'billiards') && PLAY_GAMES.every(game => ['billiards', 'cards'].includes(game.id)));
check('16 разных шаров', new Set(state.balls.map(b => b.id)).size === 16);
check('одинаковое семя даёт одинаковый стол', JSON.stringify(state) === JSON.stringify(initPool('repeatable', ['alice', 'bob'])));
check('восьмёрка в центре пирамиды', state.balls.find(b => b.id === 8)?.x === state.balls[5].x);
check('в задних углах разные группы', groupOfBall(state.balls[11].id) !== groupOfBall(state.balls[15].id));
check('чужой ход запрещён', !!billiards.why(state, 'bob', shot));
for (const move of [{ ...shot, power: Infinity }, { ...shot, angle: NaN }, { ...shot, power: -1 }, { ...shot, spin: 2 }]) check('некорректный удар отклонён', !!billiards.why(state, 'alice', move));
const sim = simulateShot(state.balls, shot);
check('физика детерминирована', JSON.stringify(sim) === JSON.stringify(simulateShot(state.balls, shot)));
check('разбой действительно сталкивает и разбрасывает шары', sim.firstHit !== null && sim.rails.length >= 4);
check('анимация имеет начало и конец', sim.frames[0].t === 0 && sim.frames.at(-1)?.t === sim.durationMs && sim.durationMs > 500);
check('исходный стол не изменён симуляцией', JSON.stringify(state) === JSON.stringify(initPool('repeatable', ['alice', 'bob'])));
check('все координаты конечны и внутри стола', sim.balls.every(b => Number.isFinite(b.x) && Number.isFinite(b.y) && b.x >= 12 && b.x <= 988 && b.y >= 12 && b.y <= 488));
const headOn = simulateShot([{ id: 0, x: 200, y: 250, pocketed: false }, { id: 1, x: 270, y: 250, pocketed: false }], { ...shot, power: 0.2 });
check('столкновение передаёт движение объектному шару', headOn.firstHit === 1 && headOn.balls[1].x > 290);
const scratch = simulateShot([{ id: 0, x: 500, y: 120, pocketed: false }], { ...shot, angle: -Math.PI / 2, power: 0.2 });
check('биток падает в среднюю лузу', scratch.pocketed.includes(0));
const rulesState: PoolState = { ...state, breaking: false };
const result = (changes: Partial<ShotSimulation> = {}): ShotSimulation => ({ balls: state.balls.map(b => ({ ...b })), firstHit: 1, pocketed: [], railAfterHit: true, rails: [1], durationMs: 1000, frames: [], ...changes });
let next = resolvePoolShot(rulesState, result({ pocketed: [1] }));
check('забивание на открытом столе назначает группы', next.groups[0] === 'solids' && next.groups[1] === 'stripes');
check('свой забитый шар сохраняет ход', next.turn === 0);
next = resolvePoolShot(rulesState, result({ pocketed: [1, 9] }));
check('обе группы за один удар оставляют стол открытым', next.groups.every(group => !group));
next = resolvePoolShot(rulesState, result({ pocketed: [0] }));
check('scratch отдаёт сопернику биток с руки', next.turn === 1 && next.ballInHand && next.balls.find(b => b.id === 0)?.pocketed === true);
check('удар до постановки битка запрещён', !!billiards.why(next, 'bob', shot));
check('нельзя поставить биток на другой шар', !canPlaceCue(next.balls, 680, 250));
check('нельзя поставить биток за столом', !canPlaceCue(next.balls, -1, 50));
check('свободное место разрешено', canPlaceCue(next.balls, 300, 300));
next = billiards.apply(next, 'bob', { type: 'place', x: 300, y: 300 });
check('постановка не расходует ход', next.turn === 1 && !next.ballInHand && next.shots === 1);
const grouped: PoolState = { ...rulesState, groups: ['solids', 'stripes'] };
check('первый чужой шар является фолом', resolvePoolShot(grouped, result({ firstHit: 9 })).ballInHand);
check('нет борта и забитых шаров является фолом', resolvePoolShot(grouped, result({ railAfterHit: false })).ballInHand);
check('нет контакта является фолом', resolvePoolShot(grouped, result({ firstHit: null })).ballInHand);
check('ранняя восьмёрка проигрывает', resolvePoolShot(grouped, result({ firstHit: 8, pocketed: [8] })).winner === 2);
const cleared = { ...grouped, balls: grouped.balls.map(b => ({ ...b, pocketed: b.id >= 1 && b.id <= 7 })) };
check('законная последняя восьмёрка выигрывает', resolvePoolShot(cleared, result({ firstHit: 8, pocketed: [8] })).winner === 1);
check('восьмёрка с битком проигрывает', resolvePoolShot(cleared, result({ firstHit: 8, pocketed: [8, 0] })).winner === 2);
check('восьмёрка на разбое возвращается на стол', !resolvePoolShot(state, result({ firstHit: 8, pocketed: [8] })).done);
check('группы не назначаются на разбое', resolvePoolShot(state, result({ pocketed: [1] })).groups.every(group => !group));
check('недостаточный разбой даёт фол', resolvePoolShot(state, result({ rails: [1, 2, 3] })).ballInHand);
console.log(`Бильярд: ${checks} проверок пройдено`);
