import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { WindowsFilesService, hashWindowsBytes } from '../electron/filesystem/service';
import { inspectWindowsTree, copyWindowsTree, cleanCreatedWindowsTree } from '../electron/filesystem/tree';
import { resolveSafePath, validateWindowsName } from '../electron/filesystem/paths';

let passed = 0;
function check(condition: unknown, message: string) { assert.ok(condition, message); passed++; console.log(`✓ ${message}`); }
async function rejects(work: () => Promise<unknown>, code: string, message: string) {
  await assert.rejects(work, (error: any) => error.code === code); passed++; console.log(`✓ ${message}`);
}
async function main() {
const sandbox = await fs.mkdtemp(path.join(os.tmpdir(), 'flux-windows-files-test-'));
let service: WindowsFilesService;
try {
  const desktop = path.join(sandbox, 'desktop'); const userData = path.join(sandbox, 'flux-data'); const outside = path.join(sandbox, 'outside');
  await fs.mkdir(desktop); await fs.mkdir(outside); await fs.mkdir(path.join(desktop, 'Проект'));
  await fs.writeFile(path.join(outside, 'private.txt'), 'секрет вне корня');
  await fs.writeFile(path.join(desktop, 'Проект', 'Исходный.md'), 'оригинал');
  const notifications: any[] = []; const trashed: string[] = []; const revealed: string[] = []; const opened: string[] = [];
  const deps = { userData, knownFolders: { desktop }, trashItem: async (filename: string) => { trashed.push(filename); await fs.rename(filename, `${filename}.trash-test`); }, showItemInFolder: (filename: string) => { revealed.push(filename); }, openPath: async (filename: string) => { opened.push(filename); return ''; }, onChanged: (event: any) => notifications.push(event) };
  service = await WindowsFilesService.create(deps);
  const roots = await service.roots(); const rootId = roots[0].id;
  check(roots.length === 1 && roots[0].kind === 'desktop' && !('path' in roots[0]), 'Корень отдаёт capability без абсолютного пути');
  const project = { rootId, relativePath: 'Проект' }; const original = { rootId, relativePath: 'Проект/Исходный.md' };
  check(await service.iconPath(original) === path.join(desktop, 'Проект', 'Исходный.md'), 'Системный значок получает только проверенный путь оригинала');
  check(await service.iconPath(project) === path.join(desktop, 'Проект'), 'Папка тоже получает настоящий системный значок');
  await rejects(() => service.iconPath({ rootId: 'unknown', relativePath: '' }), 'UNKNOWN_ROOT', 'Запрос значка не выдаёт доступ к неизвестному корню');
  await rejects(() => service.iconPath({ rootId, relativePath: '../outside/private.txt' }), 'INVALID_NAME', 'Запрос значка не обходит границу подключённой папки');
  const listing = await service.list(project); check(listing.entries[0].name === 'Исходный.md', 'Перечисляются реальные файлы с кириллицей');
  const read = await service.read(original); check(Buffer.from(read.base64, 'base64').toString() === 'оригинал', 'Чтение возвращает настоящие байты');
  await rejects(() => service.read({ rootId: 'unknown', relativePath: '' }), 'UNKNOWN_ROOT', 'Произвольный корень отклонён');
  await rejects(() => service.read({ rootId, relativePath: '../outside/private.txt' }), 'INVALID_NAME', 'Выход через .. отклонён');
  await rejects(() => service.read({ rootId, relativePath: '/etc/passwd' }), 'INVALID_PATH', 'Абсолютный путь отклонён');
  await rejects(() => service.read({ rootId, relativePath: 'Проект/Исходный.md:stream' }), 'INVALID_NAME', 'NTFS alternate stream отклонён');
  await rejects(() => service.read({ rootId, relativePath: '\\\\server\\share' }), 'INVALID_PATH', 'Неподключённый UNC отклонён');
  for (const name of ['CON', 'con.txt', 'COM1.txt', 'LPT9', 'NUL', 'bad.', 'bad ', 'a/b', 'a\\b', 'a:b', '..', '', 'a\u0000b']) { assert.throws(() => validateWindowsName(name)); passed++; }
  await fs.symlink(outside, path.join(desktop, 'link'), 'junction');
  await rejects(() => service.iconPath({ rootId, relativePath: 'link/private.txt' }), 'LINK_BLOCKED', 'Получение значка тоже отклоняет внешний junction');
  await rejects(() => service.read({ rootId, relativePath: 'link/private.txt' }), 'LINK_BLOCKED', 'Junction не даёт читать внешний файл');
  check((await service.list({ rootId, relativePath: '' })).entries.some(item => item.kind === 'link' && item.name === 'link'), 'Ссылка показана без обхода содержимого');
  const update = Buffer.from('новая версия').toString('base64');
  const concurrent = await Promise.allSettled([service.write(original, update, read.sha256), service.write(original, Buffer.from('параллельная версия').toString('base64'), read.sha256)]);
  if (concurrent.filter(item => item.status === 'fulfilled').length !== 1) console.error('CAS outcomes:', JSON.stringify(concurrent.map(item => item.status === 'fulfilled' ? { status: item.status, sha256: item.value.sha256 } : { status: item.status, code: item.reason?.code, message: item.reason?.message, nativeDiagnostic: item.reason?.nativeDiagnostic })));
  check(concurrent.filter(item => item.status === 'fulfilled').length === 1, 'При двух CAS-сохранениях одной версии записывает только один');
  check(concurrent.some(item => item.status === 'rejected' && item.reason.code === 'CONFLICT'), 'Второе CAS-сохранение получает конфликт');
  const fresh = await service.read(original); check(fresh.fileId === read.fileId, 'Атомарное сохранение сохраняет стабильный идентификатор');
  await fs.writeFile(path.join(desktop, 'Проект', 'Исходный.md'), 'правки Word');
  await rejects(() => service.write(original, update, fresh.sha256), 'CONFLICT', 'Внешние изменения Word не перезаписываются');
  check(await fs.readFile(path.join(desktop, 'Проект', 'Исходный.md'), 'utf8') === 'правки Word', 'После конфликта внешний оригинал сохранён');
  const properties = await service.setMetadata(original, { tags: ['AHU1', 'AHU1'], projectIds: ['project1'], revision: 'B', responsible: 'Инженер' });
  check(properties.tags.length === 1, 'Свойства Flux хранятся отдельно и удаляют дубли тегов');
  const moved = await service.rename(original, 'Переименованный.md'); check((await service.metadata(moved.ref)).revision === 'B', 'Переименование сохраняет ревизию и историю');
  check(moved.file.fileId === read.fileId, 'Переименование сохраняет идентичность');
  const copy = await service.copy(moved.ref, project, 'Копия.md'); check(copy.file.fileId !== moved.file.fileId && !(await service.metadata(copy.ref)).tags.length, 'Копия получает отдельную идентичность без молчаливого переноса тегов');
  await rejects(() => service.copy(moved.ref, project, 'Копия.md'), 'EEXIST', 'Копирование не перезаписывает существующую цель');
  await rejects(() => service.move(moved.ref, project, 'Копия.md'), 'EEXIST', 'Перенос не заменяет существующий файл');
  const content = Buffer.from('содержимое черновика').toString('base64');
  const published = await service.publish(project, 'Черновик.md', content, 'draft-1');
  check(published.file.sha256 === hashWindowsBytes(Buffer.from('содержимое черновика')), 'Черновик публикуется в запомненную папку');
  check((await service.publish(project, 'Другое имя.md', content, 'draft-1')).alreadyPublished, 'Повторная публикация не создаёт второй файл');
  await rejects(() => service.publish(project, 'Черновик.md', content, 'draft-2'), 'EEXIST', 'Новый черновик не заменяет существующий файл');
  await rejects(() => service.publish(project, 'Черновик.md', Buffer.from('другие правки').toString('base64'), 'draft-1'), 'ALREADY_PUBLISHED', 'После публикации нельзя обойти CAS другой версией черновика');
  const draft = await service.createDraft(project, 'Личный черновик.md', Buffer.from('локально').toString('base64'));
  check(draft.file.storage === 'flux' && draft.ref.draftId, 'Локальный черновик имеет отдельную идентичность и признак Flux');
  check(!(await fs.readdir(path.join(desktop, 'Проект'))).includes('Личный черновик.md'), 'Черновик не создаёт файл в Windows до публикации');
  check((await service.list(project)).entries.some(item => item.storage === 'flux' && item.draftId === draft.ref.draftId), 'Черновик виден рядом с настоящими файлами');
  await rejects(() => service.createDraft(project, 'личный черновик.md', ''), 'EEXIST', 'Имена черновиков сравниваются без учёта регистра Windows');
  await rejects(() => service.open(draft.ref), 'DRAFT_NOT_PUBLISHED', 'Системная программа не получает внутренний файл черновика');
  const draftEdited = await service.write(draft.ref, Buffer.from('правки черновика').toString('base64'), draft.file.sha256);
  check(draftEdited.fileId === draft.file.fileId, 'CAS-сохранение черновика сохраняет идентичность');
  await service.setMetadata(draft.ref, { tags: ['AHU-2'], projectIds: ['project2'], revision: 'C', responsible: 'Автор' });
  const draftRenamed = await service.rename(draft.ref, 'Финальный черновик.md');
  check((await service.read(draft.ref)).name === 'Финальный черновик.md', 'Старая ссылка черновика следует за его переименованием');
  service.close(); service = await WindowsFilesService.create(deps);
  check(Buffer.from((await service.read(draft.ref)).base64, 'base64').toString() === 'правки черновика', 'Локальный черновик и его правки переживают перезапуск');
  const draftPublication = await service.publishDraft(draft.ref);
  check(draftPublication.ref.relativePath === 'Проект/Финальный черновик.md' && draftPublication.file.storage === 'windows', 'Публикация создаёт настоящий файл в сохранённом родителе');
  check(draftPublication.file.fileId === draft.file.fileId && (await service.metadata(draftPublication.ref)).revision === 'C', 'Публикация переносит идентичность, теги и ревизию черновика');
  check(!(await service.list(project)).entries.some(item => item.draftId === draft.ref.draftId), 'После публикации остаётся одна карточка файла');
  check((await service.publishDraft(draft.ref)).alreadyPublished, 'Повторная публикация существующего черновика идемпотентна');
  const afterPublish = await service.read(draft.ref);
  await service.write(draft.ref, Buffer.from('правки уже Windows-файла').toString('base64'), afterPublish.sha256);
  check(await fs.readFile(path.join(desktop, 'Проект', 'Финальный черновик.md'), 'utf8') === 'правки уже Windows-файла', 'Сохранение старой ссылки после публикации обновляет Windows-оригинал');
  const doomedDraft = await service.createDraft(project, 'Удаляемый.md', Buffer.from('не публиковать').toString('base64'));
  const trashCount = trashed.length; await service.trash(doomedDraft.ref);
  check(trashed.length === trashCount && !(await service.list(project)).entries.some(item => item.draftId === doomedDraft.ref.draftId), 'Удаление черновика не затрагивает корзину и файлы Windows');
  check((await service.draftTrash()).some(item => item.ref.draftId === doomedDraft.ref.draftId), 'Удалённый черновик доступен в локальной корзине Flux');
  const restoredDraft = await service.restoreDraft(doomedDraft.ref);
  check(Buffer.from(restoredDraft.file.base64, 'base64').toString() === 'не публиковать' && restoredDraft.file.fileId === doomedDraft.file.fileId, 'Восстановление локальной корзины сохраняет байты и идентичность');
  await service.mkdir({ rootId, relativePath: '' }, 'Дерево');
  await service.mkdir({ rootId, relativePath: 'Дерево' }, 'Вложенная');
  await fs.writeFile(path.join(desktop, 'Дерево', 'Вложенная', 'Данные.txt'), 'дерево данных');
  const nestedRef = { rootId, relativePath: 'Дерево/Вложенная/Данные.txt' };
  await service.setMetadata(nestedRef, { tags: ['CHILD'], projectIds: [], revision: 'D', responsible: '' });
  const treeDraft = await service.createDraft({ rootId, relativePath: 'Дерево/Вложенная' }, 'Черновик дерева.md', Buffer.from('дочерний черновик').toString('base64'));
  const folderCopy = await service.copy({ rootId, relativePath: 'Дерево' }, { rootId, relativePath: '' }, 'Копия дерева');
  check(await fs.readFile(path.join(desktop, 'Копия дерева', 'Вложенная', 'Данные.txt'), 'utf8') === 'дерево данных', 'Копирование папки проверяет байты всего дерева');
  check((await service.list({ rootId, relativePath: 'Копия дерева/Вложенная' })).entries.some(entry => entry.storage === 'flux' && entry.name === 'Черновик дерева.md' && entry.draftId !== treeDraft.ref.draftId), 'Копирование папки сохраняет локальные черновики отдельными копиями');
  await rejects(() => service.copy({ rootId, relativePath: 'Дерево' }, { rootId, relativePath: 'Дерево/Вложенная' }, 'Рекурсия'), 'RECURSIVE_TARGET', 'Папка не копируется внутрь себя');
  await rejects(() => service.copy({ rootId, relativePath: 'Дерево' }, { rootId, relativePath: '' }, 'Копия дерева'), 'EEXIST', 'Копирование дерева не заменяет существующую папку');
  const folderMove = await service.rename({ rootId, relativePath: 'Дерево' }, 'Перенесённое дерево');
  check((await service.metadata({ rootId, relativePath: 'Перенесённое дерево/Вложенная/Данные.txt' })).revision === 'D', 'Перенос папки сохраняет свойства вложенных файлов');
  const remappedDraft = service.resolveRef(treeDraft.ref);
  check(remappedDraft.relativePath === 'Перенесённое дерево/Вложенная/Черновик дерева.md', 'Перенос папки меняет родителя локального черновика');
  check((await service.publishDraft(treeDraft.ref)).ref.relativePath === remappedDraft.relativePath, 'Черновик публикуется в папку после её переноса');
  await service.mkdir({ rootId, relativePath: '' }, 'Внешний родитель');
  const externallyMovedDraft = await service.createDraft({ rootId, relativePath: 'Внешний родитель' }, 'Внешний.md', Buffer.from('родитель из Windows').toString('base64'));
  await fs.rename(path.join(desktop, 'Внешний родитель'), path.join(desktop, 'Изменено в Windows'));
  check((await service.publishDraft(externallyMovedDraft.ref)).ref.relativePath === 'Изменено в Windows/Внешний.md', 'Публикация находит родителя по идентичности после переименования из Windows');
  await fs.symlink(outside, path.join(desktop, 'Копия дерева', 'junction'), 'junction');
  await rejects(() => service.copy(folderCopy.ref, { rootId, relativePath: '' }, 'Опасная копия'), 'LINK_BLOCKED', 'Предпроверка дерева запрещает junction и не создаёт частичную копию');
  const interruptedRef = { rootId, relativePath: 'Проект/После прерывания.md' };
  await fs.writeFile(path.join(desktop, 'Проект', 'После прерывания.md'), 'готовые байты');
  const interruptedContent = await service.read(interruptedRef);
  service.state.data.publications['interrupted-complete'] = { ref: interruptedRef, sha256: interruptedContent.sha256, fileId: interruptedContent.fileId, status: 'pending' };
  await service.state.save(); service.close(); service = await WindowsFilesService.create(deps);
  check((await service.publish(project, 'После прерывания.md', interruptedContent.base64, 'interrupted-complete')).alreadyPublished, 'Журнал завершает публикацию после сбоя между записью байтов и отметкой результата');
  const partialRef = { rootId, relativePath: 'Проект/Частичный.md' };
  await fs.writeFile(path.join(desktop, 'Проект', 'Частичный.md'), 'часть');
  const partialFile = await service.read(partialRef);
  service.state.data.publications['interrupted-partial'] = { ref: partialRef, sha256: hashWindowsBytes(Buffer.from('полная версия')), fileId: partialFile.fileId, status: 'pending' };
  await service.state.save();
  await rejects(() => service.publish(project, 'Частичный.md', Buffer.from('полная версия').toString('base64'), 'interrupted-partial'), 'PUBLICATION_INCOMPLETE', 'Частичная публикация сообщает явную ошибку и не заменяет файл');
  check(await fs.readFile(path.join(desktop, 'Проект', 'Частичный.md'), 'utf8') === 'часть', 'Частично записанный файл сохранён для разбирательства');
  service.state.data.publications['interrupted-before-create'] = { ref: { rootId, relativePath: 'Проект/Ещё не создан.md' }, sha256: hashWindowsBytes(Buffer.from('после рестарта')), fileId: '', status: 'pending' };
  await service.state.save();
  check(!(await service.publish(project, 'Ещё не создан.md', Buffer.from('после рестарта').toString('base64'), 'interrupted-before-create')).alreadyPublished, 'Публикация возобновляется после сбоя до создания физического файла');
  await service.reveal(published.ref); await service.open(published.ref); check(revealed.length === 1 && opened.length === 1, 'Открытие и показ используют настоящий исходный путь');
  await service.watch(project, 7); await service.watch(project, 8); await service.unwatch(project, 7);
  await fs.writeFile(path.join(desktop, 'Проект', 'Из Windows.txt'), 'внешняя запись');
  await new Promise(resolve => setTimeout(resolve, 250));
  check(notifications.some(event => event.relativePath === 'Проект' && event.rescan), 'Наблюдатель сообщает сверку папки после внешней записи');
  service.closeOwner(8); service.close();
  service = await WindowsFilesService.create(deps);
  check((await service.roots())[0].id === rootId, 'Capability корня сохраняется после перезапуска');
  check((await service.metadata(moved.ref)).revision === 'B', 'Ревизия сохраняется после перезапуска');
  check((await service.publish(project, 'Черновик.md', content, 'draft-1')).alreadyPublished, 'Журнал публикации сохраняется после перезапуска');
  await service.trash(copy.ref); check(trashed.length >= 1 && (await service.metadata(moved.ref)).revision === 'B', 'Удаление использует корзину и не удаляет чужую историю');
  await rejects(() => service.trash({ rootId, relativePath: '' }), 'ROOT_OPERATION', 'Корень подключённой папки нельзя удалить');
  check((await fs.readdir(path.join(userData, 'windows-files-recovery'))).length > 0, 'Перед заменой сохранён восстановимый снимок');
  const cleanupSource = path.join(sandbox, 'cleanup-source'); const cleanupTarget = path.join(sandbox, 'cleanup-target');
  await fs.mkdir(cleanupSource); await fs.writeFile(path.join(cleanupSource, 'own.txt'), 'создано операцией');
  const cleanupCreated = await copyWindowsTree(cleanupSource, cleanupTarget, await inspectWindowsTree(cleanupSource));
  await fs.writeFile(path.join(cleanupTarget, 'foreign.txt'), 'новый файл пользователя');
  await cleanCreatedWindowsTree(cleanupCreated);
  check(await fs.readFile(path.join(cleanupTarget, 'foreign.txt'), 'utf8') === 'новый файл пользователя', 'Откат копирования не удаляет новые чужие файлы в папке назначения');
  const racingDraft = await service.createDraft(project, 'Параллельная публикация.md', Buffer.from('начальная версия').toString('base64'));
  const raceResults = await Promise.all([service.publishDraft(racingDraft.ref), service.write(racingDraft.ref, Buffer.from('сохранено параллельно публикации').toString('base64'), racingDraft.file.sha256)]);
  check(await fs.readFile(path.join(desktop, 'Проект', 'Параллельная публикация.md'), 'utf8') === 'сохранено параллельно публикации', 'Параллельное сохранение черновика после публикации изменяет физический оригинал');
  const temporaryRoot = path.join(sandbox, 'temporary-root'); await fs.mkdir(temporaryRoot);
  const connectedTemporary = await service.addRoot(temporaryRoot);
  await fs.rename(temporaryRoot, `${temporaryRoot}-moved`); await fs.symlink(outside, temporaryRoot, 'junction');
  await rejects(() => service.list({ rootId: connectedTemporary.id, relativePath: '' }), 'ROOT_CHANGED', 'Подмена подключённого корня ссылкой не расширяет capability');
  console.log(`ALL TESTS PASSED (${passed})`);
} finally { service?.close(); await fs.rm(sandbox, { recursive: true, force: true }); }

}
main().catch(error => { console.error(error); process.exitCode = 1; });
