'use strict';
const {app,BrowserWindow,ipcMain,dialog,clipboard,shell}=require('electron');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const setupApi=require('./setup.cjs');
const version=require('../package.json').version;
const vaultApi=require('./vault.cjs'),signing=require('./signing.cjs'),net=require('./network.cjs');
const {applyPublicConfig}=require('./public-config.cjs');
const vaultFile=path.join(os.homedir(),'.flux-owner','vault.flux-owner');
let win,fluxWin,vault=null,password='',server='',token='',user=null,exe=null,operation=null,lastActivity=Date.now();
const uiPath=path.join(__dirname,'..','ui','index.html');
let vaultExists=false,backupSession=false,setupFolder='',setupKitPath='',publicFilePath='',previousVaultPath='',setupVerified=false;
const signalProgress=(phase,current,total)=>{if(win&&!win.isDestroyed())win.webContents.send('owner:progress',{phase,current,total});};
function snapshot(){return {version,setupKitPath,publicFilePath,previousVaultPath,setupVerified,unlocked:!!vault,vaultExists,vaultPath:vaultFile,backupSession,kind:vault?.kind||'',publicKeys:vault?Object.fromEntries(Object.entries(vault.keys).map(([k,v])=>[k,v.publicHex])):{},backupOwnerPublic:vault?.backupOwnerPublic||'',licenses:vault?.licenses||[],updates:vault?.updates||[],revocations:vault?.revocations||[],server,connected:!!token,user:user?{name:user.name,role:user.role}:null,exe:exe?{name:path.basename(exe.path),size:exe.size,sha256:exe.sha256}:null};}
function requireVault(){if(!vault)throw new Error('Сначала разблокируйте хранилище.');lastActivity=Date.now();}
async function save(next){if(backupSession)throw new Error('Запасной ключ открыт временно. Основное хранилище не изменяется.');await vaultApi.atomicWrite(vaultFile,await vaultApi.encrypt(next,password));vault=next;vaultExists=true;}
function requireIdle(){if(operation)throw new Error('Дождитесь завершения текущей операции или отмените её.');}
async function busy(fn){requireIdle();const controller=new AbortController();operation=controller;try{return await fn(controller.signal);}finally{operation=null;signalProgress('',0,0);}}
function disconnect(){token='';server='';user=null;if(fluxWin&&!fluxWin.isDestroyed())fluxWin.close();fluxWin=null;}
function lock(){operation?.abort();vault=null;password='';backupSession=false;setupVerified=false;exe=null;disconnect();if(win&&!win.isDestroyed())win.webContents.send('owner:locked');}
async function confirm(message,detail){const r=await dialog.showMessageBox(win,{type:'question',buttons:['Отмена','Подтвердить'],defaultId:0,cancelId:0,noLink:true,message,detail});return r.response===1;}
async function exportEncrypted(payload,phrase,title,defaultPath){vaultApi.passwordCheck(phrase);const r=await dialog.showSaveDialog(win,{title,defaultPath,filters:[{name:'Зашифрованные ключи Flux',extensions:['flux-owner']}]});if(r.canceled||!r.filePath)return false;protectLocalVault(r.filePath);await vaultApi.atomicWrite(r.filePath,await vaultApi.encrypt(payload,phrase));return true;}
function protectLocalVault(file){const normalize=p=>process.platform==='win32'?path.resolve(p).toLowerCase():path.resolve(p);if(normalize(file)===normalize(vaultFile))throw new Error('Нельзя перезаписать рабочее хранилище экспортом. Выберите другую папку или имя файла.');}
function clearSetup(){setupKitPath='';publicFilePath='';previousVaultPath='';setupVerified=false;}
function safeText(value,max=20000){if(typeof value!=='string'||value.length>max)throw new Error('Некорректные данные формы.');return value;}
const actions={
  state:async()=>snapshot(),
  chooseSetupFolder:async()=>{requireIdle();const r=await dialog.showOpenDialog(win,{title:'Выберите папку для полного комплекта восстановления',properties:['openDirectory','createDirectory']});if(r.canceled||!r.filePaths?.[0])return {canceled:true};setupFolder=r.filePaths[0];return {folderPath:setupFolder};},
  setup:async a=>{requireIdle();const phrase=safeText(a.password,1024);vaultApi.passwordCheck(phrase);if(phrase!==a.confirmPassword)throw new Error('Пароли не совпадают. Повторите пароль точно, включая пробелы и раскладку.');if(!setupFolder)throw new Error('Сначала выберите папку для резервных копий.');if(vaultExists){if(a.replaceExisting!==true)throw new Error('Подтвердите создание новых ключей вместо существующих.');if(!await confirm('Создать новые ключи владельца?', 'Прежнее хранилище сохранится в папке previous рядом с рабочим файлом. Старые лицензии и подписи не будут подходить к новым ключам. Потребуется новая сборка Flux и перевыпуск лицензий.'))return {canceled:true};}return busy(async signal=>{const result=await setupApi.createSetup({folder:setupFolder,localFile:vaultFile,password:phrase,signal});disconnect();exe=null;vault=result.main;password=phrase;vaultExists=true;backupSession=false;setupKitPath=result.kitPath;publicFilePath=result.publicFilePath;previousVaultPath=result.previousVaultPath;setupVerified=false;lastActivity=Date.now();return snapshot();});},
  verifySetup:async a=>{requireVault();if(!setupKitPath||backupSession)throw new Error('Сначала создайте новый комплект ключей.');return busy(async signal=>{setupVerified=false;const loaded=await vaultApi.readVault(vaultFile,safeText(a.password,1024));if(!setupApi.sameKeys(loaded,vault))throw new Error('Рабочее хранилище изменилось. Откройте его заново.');await setupApi.verifyKit(setupKitPath,a.password,loaded);signal.throwIfAborted();setupVerified=true;return snapshot();});},
  showSetupFolder:async()=>{requireIdle();if(!setupKitPath)throw new Error('Комплект восстановления ещё не создан.');const error=await shell.openPath(setupKitPath);if(error)throw new Error('Не удалось открыть папку: '+error);return {opened:true};},
  create:async a=>{requireIdle();if(vaultExists)throw new Error('Хранилище уже существует. Разблокируйте его или импортируйте резервную копию.');vaultApi.passwordCheck(a.password);vaultApi.passwordCheck(a.backupPassword);if(a.password===a.backupPassword)throw new Error('Для запасного ключа используйте другую фразу-пароль.');const generated=vaultApi.generateVaults();const saved=await exportEncrypted(generated.backup,a.backupPassword,'Сохранить запасной ключ отдельно, на отключаемый носитель','Flux-Owner-Запасной.flux-owner');if(!saved)return {canceled:true};password=a.password;try{await save(generated.main);}catch(e){password='';throw e;}return snapshot();},
  unlock:async a=>{requireIdle();const loaded=await vaultApi.readVault(vaultFile,safeText(a.password,1024));disconnect();exe=null;vault=loaded;backupSession=loaded.kind==='backup';password=backupSession?'':a.password;lastActivity=Date.now();return snapshot();},
  openBackup:async a=>{requireIdle();const selected=await dialog.showOpenDialog(win,{title:'Открыть запасной ключ без замены основного хранилища',properties:['openFile'],filters:[{name:'Запасной ключ владельца Flux',extensions:['flux-owner']}]});if(selected.canceled)return {canceled:true};const loaded=await vaultApi.readVault(selected.filePaths[0],safeText(a.password,1024));if(loaded.kind!=='backup')throw new Error('Выбран основной файл. Откройте локальное хранилище или восстановите полную резервную копию.');disconnect();exe=null;clearSetup();vault=loaded;password='';backupSession=true;lastActivity=Date.now();return snapshot();},
  lock:async()=>{lock();return snapshot();},
  import:async a=>{requireIdle();const selected=await dialog.showOpenDialog(win,{title:'Импортировать зашифрованное хранилище',properties:['openFile'],filters:[{name:'Ключи владельца Flux',extensions:['flux-owner']}]});if(selected.canceled)return {canceled:true};const loaded=await vaultApi.readVault(selected.filePaths[0],safeText(a.importPassword,1024));if(loaded.kind==='backup'&&vaultExists)throw new Error('Запасной ключ не заменяет основное хранилище лицензий и обновлений. Используйте «Открыть запасной ключ без замены».');if(loaded.kind!=='main')throw new Error('Аварийный ключ используется только для временного входа. Для восстановления нужна полная копия.');vaultApi.passwordCheck(a.password);if(vaultExists&&!await confirm('Восстановить полную резервную копию?','Прежнее хранилище сохранится отдельно. Рабочие ключи и реестр будут восстановлены из выбранной полной копии.'))return {canceled:true};if(vaultExists)await setupApi.archiveExisting(vaultFile);const oldPassword=password,oldBackupSession=backupSession;password=a.password;backupSession=false;try{await save(loaded);}catch(e){password=oldPassword;backupSession=oldBackupSession;throw e;}clearSetup();disconnect();exe=null;return snapshot();},
  export:async a=>{requireVault();requireIdle();const saved=await exportEncrypted(vault,a.password,'Экспорт резервной копии','Flux-Owner-Резервная.flux-owner');return {saved,canceled:!saved};},
  changePassword:async a=>{requireVault();requireIdle();vaultApi.passwordCheck(a.password);const old=password;password=a.password;try{await save(vault);}catch(e){password=old;throw e;}return snapshot();},
  publicExport:async()=>{requireVault();requireIdle();const config=signing.publicConfig(vault);const r=await dialog.showSaveDialog(win,{title:'Открытые ключи для сборки Flux',defaultPath:'flux-public-keys.json',filters:[{name:'Открытый конфиг',extensions:['json']}]});if(r.canceled)return {canceled:true};protectLocalVault(r.filePath);await vaultApi.atomicWrite(r.filePath,JSON.stringify(config,null,2));return {saved:true,config};},
  publicApply:async()=>{requireVault();requireIdle();const config=signing.publicConfig(vault);const r=await dialog.showOpenDialog(win,{title:'Выберите папку исходников Flux',properties:['openDirectory']});if(r.canceled)return {canceled:true};if(!await confirm('Закрепить открытые ключи в исходниках Flux?',`Папка: ${r.filePaths[0]}\nИзменятся только license/ownerKey.ts и electron/updateKey.ts. Закрытые ключи не копируются. После этого нужна новая первоначальная сборка и ручная установка.`))return {canceled:true};return applyPublicConfig(r.filePaths[0],config);},
  request:async a=>{requireVault();return signing.safeRequest(safeText(a.code,1024*1024));},
  issue:async a=>{requireVault();requireIdle();const next=structuredClone(vault);const issued=signing.issueLicense(next,a);await save(next);return issued;},
  revoke:async a=>{requireVault();requireIdle();if(!await confirm('Отозвать выбранные лицензии?','Отзыв накопительный: выпущенный подписанный список нельзя уменьшить. Отправьте его администратору компании или опубликуйте через подключённый сервер.'))return {canceled:true};const next=structuredClone(vault);const issued=signing.revokeLicenses(next,a);await save(next);return issued;},
  copy:async a=>{safeText(a.text,1024*1024);clipboard.writeText(a.text);return {copied:true};},
  chooseExe:async()=>{requireVault();return busy(async signal=>{const r=await dialog.showOpenDialog(win,{title:'Выберите portable Flux для сотрудников',properties:['openFile'],filters:[{name:'Windows EXE',extensions:['exe']}]});if(r.canceled)return {canceled:true};exe=null;exe=await signing.inspectExe(r.filePaths[0],(n,total)=>signalProgress('Проверка EXE',n,total),signal);return snapshot();});},
  signUpdate:async a=>{requireVault();if(!exe)throw new Error('Выберите EXE.');return busy(async signal=>{const verified=await signing.inspectExe(exe.path,(n,total)=>signalProgress('Проверка EXE',n,total),signal);if(verified.sha256!==exe.sha256)throw new Error('EXE изменился. Выберите его заново.');const signed=signing.signUpdate(vault,verified,safeText(a.version,80));const r=await dialog.showSaveDialog(win,{title:'Сохранить подпись обновления',defaultPath:`Flux-${a.version}.flux-sig`,filters:[{name:'Подпись обновления',extensions:['flux-sig']}]});if(r.canceled)return {canceled:true};await vaultApi.atomicWrite(r.filePath,signed.signature+'\n');const next=structuredClone(vault);next.updates.push({...signed.payload,signature:signed.signature,name:path.basename(exe.path),published:false});await save(next);return signed;});},
  connect:async a=>{requireVault();return busy(async signal=>{disconnect();const origin=net.serverUrl(safeText(a.server,1000));const packet=await net.request(origin,'/api/owner/challenge',{signal});const sig=net.signChallenge(packet,origin,vault.keys.owner.privatePem);const result=await net.request(origin,'/api/owner/login',{method:'POST',body:{nonce:packet.nonce,sig},signal});if(typeof result.token!=='string'||result.token.length<16||result.token.length>10000||result.user?.role!=='OWNER')throw new Error('Сервер не подтвердил вход владельца.');server=origin;token=result.token;user=result.user;return snapshot();});},
  disconnect:async()=>{disconnect();return snapshot();},
  publish:async a=>{requireVault();if(!exe||!token)throw new Error('Выберите EXE и войдите на сервер компании.');const version=safeText(a.version,80),changelog=safeText(a.changelog);if(!changelog.trim())throw new Error('Добавьте описание изменений для сотрудников.');signing.signUpdate(vault,exe,version);if(!await confirm('Подписать и опубликовать обновление?',`Сервер: ${server}\nВерсия: ${version}\nФайл: ${path.basename(exe.path)} (${exe.size} байт)\nSHA-256: ${exe.sha256}\n\n${changelog}`))return {canceled:true};return busy(async signal=>{const verified=await signing.inspectExe(exe.path,(n,total)=>signalProgress('Проверка EXE',n,total),signal);if(verified.sha256!==exe.sha256)throw new Error('EXE изменился. Выберите его заново.');const signed=signing.signUpdate(vault,verified,version);await net.request(server,`/api/updates/upload?version=${version}`,{method:'POST',token,file:verified,signal,onProgress:(n,total)=>signalProgress('Загрузка в БД',n,total)});const published=await net.request(server,'/api/updates',{method:'POST',token,body:{version,changelog,signature:signed.signature},signal});const next=structuredClone(vault);next.updates.push({...signed.payload,signature:signed.signature,name:path.basename(exe.path),published:true,server});await save(next);return {published,signature:signed.signature};});},
  publishRevocation:async a=>{requireVault();if(!token)throw new Error('Войдите на сервер компании.');const saved=vault.revocations.find(p=>p.code===a.code);if(!saved)throw new Error('Список отзыва не найден в вашем реестре.');if(!await confirm('Передать список отзыва серверу?',`Сервер: ${server}\nУстановка: ${saved.inst}\nОтозванных ключей: ${saved.ids.length}\nНомер списка: ${saved.seq}`))return {canceled:true};return busy(signal=>net.request(server,'/api/license/revocations',{method:'POST',token,body:{code:saved.code},signal}));},
  withdrawUpdate:async a=>{requireVault();if(!token)throw new Error('Войдите на сервер компании.');const version=safeText(a.version,80);if(!/^\d+\.\d+\.\d+(?:-[A-Za-z0-9.]+)?$/.test(version))throw new Error('Неверная версия.');if(!await confirm(`Отозвать обновление ${version}?`,`Сервер: ${server}\nНовые скачивания этого выпуска прекратятся. Уже установленные копии сохранятся.`))return {canceled:true};return busy(signal=>net.request(server,`/api/updates/${version}`,{method:'DELETE',token,signal}));},
  cancel:async()=>{operation?.abort();return {canceled:true};},
  openFlux:async()=>{requireVault();if(!token)throw new Error('Войдите на сервер компании.');if(fluxWin&&!fluxWin.isDestroyed()){fluxWin.focus();return {opened:true};}const origin=server;fluxWin=new BrowserWindow({width:1440,height:950,minWidth:960,minHeight:640,title:'Flux — владелец',webPreferences:{contextIsolation:true,sandbox:true,nodeIntegration:false,partition:`owner-view-${crypto.randomBytes(8).toString('hex')}`}});const ses=fluxWin.webContents.session;ses.webRequest.onBeforeSendHeaders((details,callback)=>{const u=new URL(details.url);if(u.origin===origin&&(u.pathname.startsWith('/api/')||u.pathname.startsWith('/socket.io/')))details.requestHeaders.Authorization=`Bearer ${token}`;callback({requestHeaders:details.requestHeaders});});fluxWin.webContents.setWindowOpenHandler(()=>({action:'deny'}));fluxWin.webContents.on('will-navigate',(event,url)=>{if(new URL(url).origin!==origin)event.preventDefault();});await fluxWin.loadURL(origin);return {opened:true};}
};
app.whenReady().then(async()=>{
  vaultExists=await fs.stat(vaultFile).then(()=>true,()=>false);
  win=new BrowserWindow({width:1180,height:850,minWidth:860,minHeight:640,title:`Flux Владелец ${version}`,backgroundColor:'#101722',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,sandbox:true,nodeIntegration:false,webSecurity:true}});
  win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',event=>event.preventDefault());
  ipcMain.handle('owner:action',async(event,action,args={})=>{
    if(event.sender!==win.webContents||event.senderFrame!==win.webContents.mainFrame||!Object.hasOwn(actions,action))return {ok:false,error:'Недоступное действие.'};
    try{lastActivity=Date.now();const value=await actions[action](args&&typeof args==='object'?args:{});return {ok:true,value};}catch(e){return {ok:false,error:e?.message||'Операция не выполнена.'};}
  });
  await win.loadFile(uiPath);
  const timer=setInterval(()=>{if(vault&&!operation&&Date.now()-lastActivity>15*60*1000)lock();},30000);timer.unref();
  win.on('closed',()=>{lock();app.quit();});
});
app.on('window-all-closed',()=>app.quit());
